{
  "hash": "8605a2bb247fbfbb794c14719e46bbce",
  "result": {
    "engine": "knitr",
    "markdown": "# 7. Hüpoteeside testimine\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\nload(\"data/ess11_ee_clean.rdata\")\n\nvanus <- as.vector(na.omit(data$vanus))\n```\n:::\n\n\nEelmises praktikumis saime teada, kuidas hinnata ebakindlust ühe arvu ümber. Nüüd\nkasutame seda millegi konkreetse jaoks: **otsustamiseks.**\n\n## Null- ja alternatiivhüpotees\n\nPeaaegu iga statistiline test on üles ehitatud ühtemoodi. Meil on kaks väidet.\n\n* **Nullhüpotees.** See väärtus, mida me andmetes näeme, ei erine mingist kindlast\n  hüpoteetilisest väärtusest. Enamasti on see hüpoteetiline väärtus **null**. Lühidalt:\n  **seost ei ole.**\n* **Alternatiivne hüpotees.** Erinevus on olemas. Lühidalt: **seos on olemas.**\n\nTest ei tõesta kumbagi. Ta ütleb ainult: **kui nullhüpotees oleks realsuses tõsi, kui tõenäoline\noleks siis näha andmetes seda, mida me näeme?** Kui see tõenäosus on väga väike, siis järeldame,\net nullhüpotees ilmselt ei kehti. Ehk siis kui see tõenäosus, et me näeme oma andmetes seda, mida me näeme olukorras, kus pärielt on tõene null-hüpotees, on väga väike, siis me järeldame, et null-hüpotees ei ole tõene. Meie andmed ei ole väga suure tõenäosusega tulnud populatsioonist, kus null hüpotees on tõene. \n\n## Mis on p-väärtus?\n\nEnne kui ühtegi testi teeme, tuleb selgeks saada see arv, mille järgi me kõik oma otsused teeme.\n\n**P-väärtus on tõenäosus näha oma andmetes sellist tulemust (või veel ekstreemsemat), kui nullhüpotees oleks tõsi.**\n\nLoe see lause veel kord läbi. Ta on tinglik: \"kui nullhüpotees oleks tõsi\". P-väärtus ei ütle sulle, kas nullhüpotees on tõsi — ta ütleb, kui hästi sinu andmed sellega kokku sobiksid.\n\nMõtle sellest nii. Sa oletad korraks, et seost ei ole. Siis vaatad oma andmeid ja küsid: **kui ebatavalised need andmed sellise oletuse juures oleksid?**\n\n* Kui p-väärtus on **suur** (näiteks 0,60), siis on sinu andmed sellise oletusega täiesti kooskõlas. Midagi kummalist ei ole.\n* Kui p-väärtus on **väike** (näiteks 0,002), siis oleksid sinu andmed sellise oletuse juures väga ebatavalised. Järelikult on oletus ilmselt vale ja seos on olemas.\n\nPraktilises kasutuses tõlgendatakse teda lühemalt: **tõenäosus eksida, kui me väidame, et seos on päriselt olemas.**\n\n> **Statistiline tava on 5%.** Kui p-väärtus on väiksem kui 0,05 — ehk tõenäosus eksida on alla 5% — siis ütleme, et erinevus on **statistiliselt oluline**. See piir ei ole loodusseadus, vaid kokkulepe. Mõnes valdkonnas kasutatakse rangemaid piire (1% või 0,1%).\n>\n> Sama asja kohta öeldakse vahel ka \"95% usaldusnivoo\" — see on lihtsalt teine pool samast arvust. 5% tõenäosus eksida tähendab 95% kindlust.\n\n**Mida p-väärtus EI ole.** Kolm väärarusaama, mis on nii levinud, et neid tasub eraldi välja tuua.\n\n* Ta **ei ole** tõenäosus, et nullhüpotees on tõsi.\n* Ta **ei ütle midagi selle kohta, kui suur** seos on. Väga väike p-väärtus võib käia täiesti tühise erinevuse kohta — vaata allpool osa statistilise ja sisulise olulisuse kohta.\n* Ta **ei ole** tõenäosus, et sinu tulemus kordub, kui uuringut korrata.\n\n> **P-väärtus on kogu järgneva kursuse võti.** Ta näeb täpselt samasugune välja ja teda tõlgendatakse täpselt sama moodi t-testi, korrelatsiooni, regressiooni ja logistilise regressiooni juures. Kui ta siin selgeks saab, siis on kõik ülejäänu variatsioon samal teemal.\n\n## Ühe grupi t-test\n\nAlustame kõige lihtsamast juhtumist. Meie valimi keskmine vanus on 50,1. **Kas Eesti\nelanike keskmine vanus võiks tegelikult olla 52?**\n\n::: {.panel-tabset}\n\n## Lihtsam seletus\n\nEelmises praktikumis arvutasime usaldusvahemiku. Ta ütles meile, kuhu tõene keskmine\ntõenäoliselt jääb.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nk_vanus <- mean(vanus)\nsviga <- sd(vanus) / length(vanus)^0.5\n\nc(\n  alumine = k_vanus - 1.96 * sviga,\n  keskmine = k_vanus,\n  ylemine = k_vanus + 1.96 * sviga\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n##  alumine keskmine  ylemine \n## 49.08749 50.07309 51.05870\n```\n\n\n:::\n:::\n\n\nTõene keskmine vanus jääb 95% tõenäosusega vahemikku 49,1 kuni 51,1.\n\n**Kas 52 jääb sellesse vahemikku?** Ei jää. Ta on üleval pool.\n\nJa see ongi hüpoteesi test. Kogu ülejäänu on selle sama küsimuse täpsem sõnastus.\n\n* Kui võrreldav väärtus jääb **usaldusvahemikku sisse**, siis ei saa me välistada, et ta\n  ongi tõene väärtus. Erinevus ei ole statistiliselt oluline.\n* Kui ta jääb **väljapoole**, siis on ta meie andmetega raskesti ühildatav. Erinevus on\n  statistiliselt oluline.\n\nProovime nüüd väärtust 50:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nc(alumine = k_vanus - 1.96 * sviga, ylemine = k_vanus + 1.96 * sviga)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n##  alumine  ylemine \n## 49.08749 51.05870\n```\n\n\n:::\n:::\n\n\nArv 50 jääb vahemikku sisse. Seega ei saa me öelda, et Eesti keskmine vanus erineks\n50-st.\n\n> **Pane tähele, mida me ei öelnud.** Me ei öelnud, et keskmine vanus **on** 50. Me\n> ütlesime, et me ei suuda välistada, et ta on 50. Statistiline test ei tõesta kunagi\n> nullhüpoteesi — ta ainult ei suuda teda ümber lükata.\n\nR teeb selle kõik ühe funktsiooniga ära. Funktsioon `t.test()` võtab esimeseks\nargumendiks muutuja ja argumendiga `mu` öeldakse, millise väärtusega võrrelda.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(vanus, mu = 52)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## \n## \tOne Sample t-test\n## \n## data:  vanus\n## t = -3.8319, df = 1285, p-value = 0.0001333\n## alternative hypothesis: true mean is not equal to 52\n## 95 percent confidence interval:\n##  49.08658 51.05961\n## sample estimates:\n## mean of x \n##  50.07309\n```\n\n\n:::\n:::\n\n\nVäljundis on kõik, mida vaja:\n\n* **`mean of x`** — meie valimi keskmine;\n* **`95 percent confidence interval`** — usaldusvahemik, sama, mille me ise arvutasime;\n* **`p-value`** — tõenäosus eksida, kui väidame, et erinevus on olemas;\n* **`t`** — mitme standardvea kaugusel võrreldav väärtus keskmisest on.\n\nP-väärtus on siin väga väike, seega erinevus on statistiliselt oluline.\n\nJa võrdlusena, väärtusega 50:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(vanus, mu = 50)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## \n## \tOne Sample t-test\n## \n## data:  vanus\n## t = 0.14536, df = 1285, p-value = 0.8845\n## alternative hypothesis: true mean is not equal to 50\n## 95 percent confidence interval:\n##  49.08658 51.05961\n## sample estimates:\n## mean of x \n##  50.07309\n```\n\n\n:::\n:::\n\n\nP-väärtus on 0,89 — palju suurem kui 0,05. Erinevus ei ole statistiliselt oluline. Ja\nusaldusvahemik on täpselt sama, mis enne, sest ta ei sõltu sellest, millega me võrdleme.\n\n## Täpsem seletus\n\nVaatame, kust p-väärtus tuleb.\n\nEsmalt: **kui kaugel on 52 meie keskmisest?**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nerinevus <- 52 - mean(vanus)\nerinevus\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## [1] 1.926905\n```\n\n\n:::\n:::\n\n\nSee arv üksi ei ütle midagi. Kaks aastat on palju või vähe sõltuvalt sellest, kui täpne\nmeie hinnang üldse on. Seega teisendame ta **standardvigadeks** — sama moodi, nagu\neelmises praktikumis tegime z-skoori.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsviga <- sd(vanus) / length(vanus)^0.5\ntskoor <- erinevus / sviga\ntskoor\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## [1] 3.831892\n```\n\n\n:::\n:::\n\n\n**See ongi t-väärtus.** Ta ütleb: võrreldav väärtus on 3,7 standardviga meie keskmisest\neemal.\n\nNüüd küsime: kui tõene keskmine oleks tõesti 52, kui tõenäoline oleks siis näha valimi keskmist, mis on nii kaugel? Selleks on funktsioon `pt()`, mis töötab nagu `pnorm()`, kuid t-jaotuse jaoks. Lisaks vajab ta argumenti `df` — vabadusastmete arvu, millest praktikumis 6 juttu oli.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvabadusastmed <- length(vanus) - 1\n\npt(tskoor, df = vabadusastmed)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## [1] 0.9999333\n```\n\n\n:::\n:::\n\n\nVaata seda arvu tähelepanelikult. Ta on peaaegu üks. Miks?\n\nSest `pt()` ütleb, kui suur osa jaotusest jääb antud väärtusest **allapoole**. Meie t-väärtus on positiivne ja suur, seega jääb temast allapoole peaaegu kogu jaotus. See ei ole see, mida me tahame teada.\n\nMeid huvitab **jaotuse ots** — kui palju on veel ekstreemsemaid väärtusi. Selleks tuleb see arv ühest lahutada.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nylemine_ots <- 1 - pt(tskoor, df = vabadusastmed)\n\nylemine_ots\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## [1] 6.665277e-05\n```\n\n\n:::\n:::\n\n\nJa kuna me ei tea ette, kas tõene väärtus on meie omast suurem või väiksem, huvitavad meid **mõlemad otsad**. Jaotus on sümmeetriline, seega korrutame selle otsa kahega.\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_vaartus <- 2 * ylemine_ots\n\np_vaartus\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## [1] 0.0001333055\n```\n\n\n:::\n:::\n\n\n**See ongi p-väärtus.** Ja ta on täpselt sama, mille `t.test()` meile andis.\n\n> **Pane see samm tähele, siin eksitakse pidevalt.** Kaks tehet käivad koos ja kumbagi ei tohi ära unustada:\n>\n> 1. **lahuta ühest** — et saada jaotuse ots, mitte kogu ülejäänud jaotus;\n> 2. **korruta kahega** — et arvestada mõlemat otsa.\n>\n> Kui sa ainult korrutad kahega, saad tulemuseks arvu, mis on suurem kui üks. **Tõenäosus ei saa kunagi olla suurem kui üks.** See on kõige lihtsam kontroll, mille sa oma arvutusele teha saad — kui p-väärtus tuleb üle ühe või alla nulli, siis on valemis viga.\n>\n> Sama tulemuse saab ka lühemalt, kui anda `pt()`-le negatiivne t-väärtus: `2 * pt(-abs(tskoor), df = vabadusastmed)`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(vanus, mu = 52)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## \n## \tOne Sample t-test\n## \n## data:  vanus\n## t = -3.8319, df = 1285, p-value = 0.0001333\n## alternative hypothesis: true mean is not equal to 52\n## 95 percent confidence interval:\n##  49.08658 51.05961\n## sample estimates:\n## mean of x \n##  50.07309\n```\n\n\n:::\n:::\n\n\n> **Mida p-väärtus tähendab?** Ta on tõenäosus näha oma andmetes sellist erinevust (või\n> veel suuremat), **kui nullhüpotees oleks tõsi**.\n>\n> Tinglikult ja praktilises kasutuses: **tõenäosus eksida, kui me väidame, et erinevus\n> on päriselt olemas.**\n>\n> Mida ta **ei** tähenda: p-väärtus ei ole tõenäosus, et nullhüpotees on tõsi. Ja ta ei\n> ütle midagi selle kohta, kui **suur** erinevus on. Väga väike p-väärtus võib käia\n> täiesti tühise erinevuse kohta.\n\nTee siinkohal mõttepaus. Selles lõigus on peidus kogu ülejäänud kursuse võti — sama\nloogika kordub korrelatsiooni, regressiooni ja logistilise regressiooni juures täpselt\nühtemoodi.\n\n:::\n\n## Kahe grupi t-test\n\nPraktikas huvitab meid harva üksiku keskmise võrdlemine mingi arvuga. Palju sagedamini\ntahame teada, **kas kaks gruppi erinevad.**\n\nKüsime: kas mehed ja naised paigutavad end vasak-parem skaalal erinevalt?\n\nVaatame kõigepealt keskmisi.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata |>\n  group_by(sugu) |>\n  summarise(\n    n = sum(!is.na(vasak_parem)),\n    keskmine = mean(vasak_parem, na.rm = TRUE),\n    sd = sd(vasak_parem, na.rm = TRUE)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## # A tibble: 2 × 4\n##   sugu      n keskmine    sd\n##   <fct> <int>    <dbl> <dbl>\n## 1 mees    523     5.86  1.99\n## 2 naine   585     5.51  1.76\n```\n\n\n:::\n:::\n\n\nErinevus on olemas, aga väike. Kas ta on piisavalt suur?\n\nNullhüpotees on, et **kahe grupi keskmiste erinevus populatsioonis on null.**\n\nKahe grupi võrdlemiseks kirjutatakse `t.test()` teistmoodi — mudeli valemina, tildega, millega tegime tutvust praktikumis 3. Vasakule poole käib pidev muutuja, mille keskmist võrreldakse, ja paremale poole grupeeriv muutuja.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntest_lr <- t.test(vasak_parem ~ sugu, data = data)\n\ntest_lr\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## \n## \tWelch Two Sample t-test\n## \n## data:  vasak_parem by sugu\n## t = 3.0745, df = 1049.6, p-value = 0.002163\n## alternative hypothesis: true difference in means between group mees and group naine is not equal to 0\n## 95 percent confidence interval:\n##  0.1262213 0.5715872\n## sample estimates:\n##  mean in group mees mean in group naine \n##            5.856597            5.507692\n```\n\n\n:::\n:::\n\n\nVäljund on sarnane, aga nüüd on näha **mõlema grupi keskmine** ja usaldusvahemik käib **nende erinevuse** kohta.\n\nJärgnevas plokis võtame testi väljundist arvud eraldi objektidesse, et neid tekstis\nkasutada. Funktsioon `signif()` ümardab tähendusrikaste numbrikohtade arvuni — erinevalt\nfunktsioonist `round()`, mis ümardab komakohtade arvuni. Väga väikeste arvude puhul on\n`signif()` mugavam.\n\n\n\nKuidas seda lugeda?\n\n* Meeste keskmine on 5.86 ja naiste oma 5.51, erinevus seega 0.35 punkti.\n* 95% usaldusvahemik erinevuse ümber on 0.13 kuni 0.57.\n* **See vahemik ei sisalda nulli.**\n* P-väärtus on 0.0022 — väiksem kui 0,05.\n\n**Järeldus: erinevus on statistiliselt oluline.** Eesti mehed paigutavad end vasak-parem skaalal keskmiselt veidi parempoolsemalt kui naised.\n\n::: {.arutelu}\n**Arutelu.** Erinevus on 0.35 punkti üheteistpunktisel skaalal. Statistiliselt on ta oluline. **Kas ta on ka sisuliselt oluline?** Mille põhjal sa seda otsustad?\n:::\n\nProovime nüüd midagi, kus tulemus on teistsugune. Vaatame suhtumist sisserändesse.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntest_ranne <- t.test(ranne ~ sugu, data = data)\n\ntest_ranne\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## \n## \tWelch Two Sample t-test\n## \n## data:  ranne by sugu\n## t = 0.17629, df = 1111.1, p-value = 0.8601\n## alternative hypothesis: true difference in means between group mees and group naine is not equal to 0\n## 95 percent confidence interval:\n##  -0.09618253  0.11517234\n## sample estimates:\n##  mean in group mees mean in group naine \n##         0.005171894        -0.004323012\n```\n\n\n:::\n:::\n\n\n\n\nSiin on pilt vastupidine. Usaldusvahemik ulatub -0.096 kuni 0.115 ja **sisaldab nulli**. P-väärtus on 0.86 — palju suurem kui 0,05.\n\n**Järeldus: erinevus ei ole statistiliselt oluline.** Meie andmed ei anna alust väita, et Eesti meeste ja naiste suhtumine sisserändesse erineks.\n\n> **Pane tähele, kuidas need kaks järeldust sõnastatud on.** Esimesel juhul ütlesime \"erinevus on olemas\". Teisel juhul **ei öelnud me, et erinevust ei ole** — ütlesime, et andmed ei anna alust väita, et ta oleks. See ei ole sõnamäng. Erinevus võib populatsioonis olemas olla, aga meie valim on liiga väike, et teda tuvastada.\n\n> **Väike tehniline märkus.** R teeb vaikimisi testi, mis ei eelda, et hajuvus on\n> mõlemas grupis võrdne (nn Welchi test). See on peaaegu alati õige valik. Kui sa tahad\n> võrdset hajuvust eeldavat testi, on selleks argument `var.equal = TRUE` — aga\n> tavaliselt ei ole seda vaja.\n\n## Statistiline ja sisuline olulisus\n\nNüüd kõige tähtsam hoiatus terves kursuses.\n\nTuleta meelde standardvea valemit: $se = sd / \\sqrt{n}$. Nimetajas on valimi suurus.\nSee tähendab, et **mida rohkem andmeid, seda väiksem standardviga** — ja seda väiksem\np-väärtus, ilma et andmetes midagi muud muutuks.\n\nVaatame, mis juhtub, kui me sama erinevust suuremas valimis vaataksime. Teeme selleks kunstlikud andmed funktsiooniga `rnorm()`, mis genereerib juhuslikke arve normaaljaotusest. Argument `mean` määrab keskmise ja esimene argument ütleb, mitu arvu teha. Funktsioon `rep()` kordab väärtusi; argument `each` ütleb, mitu korda igaüht järjest korrata.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2026)\n\n# Sama erinevus, aga kunstlikult suurendatud valim\nsuur <- data.frame(\n  x = c(rnorm(10000, mean = 5.0), rnorm(10000, mean = 5.1)),\n  grupp = rep(c(\"a\", \"b\"), each = 10000)\n)\n\nt.test(x ~ grupp, data = suur)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## \n## \tWelch Two Sample t-test\n## \n## data:  x by grupp\n## t = -8.0168, df = 19998, p-value = 1.144e-15\n## alternative hypothesis: true difference in means between group a and group b is not equal to 0\n## 95 percent confidence interval:\n##  -0.14161147 -0.08596895\n## sample estimates:\n## mean in group a mean in group b \n##        5.003674        5.117465\n```\n\n\n:::\n:::\n\n\nErinevus on 0,1 punkti — sisuliselt olematu. Aga p-väärtus on väga väike, sest juhtumeid\non 20 000.\n\n> **Piisavalt suure valimi puhul on kõik statistiliselt oluline.** Statistiline olulisus\n> ütleb ainult, et erinevus ei ole ilmselt null. Ta ei ütle **mitte midagi** selle\n> kohta, kas erinevus on piisavalt suur, et tema üle tasuks üldse rääkida.\n>\n> Seetõttu tuleb alati vaadata **ka erinevuse suurust** ja küsida, kas ta on sisuliselt\n> oluline. Kas kaks aastat keskmises vanuses on palju? Kas 0,1 punkti üheteistpunktisel\n> skaalal on midagi väärt?\n>\n> **Sellele küsimusele ei vasta statistika. Sellele vastad sina, oma valdkonna teadmiste\n> põhjal.**\n\n## Kuidas seda kirja panna\n\n::: {.callout-tip title=\"Kuidas seda kirja panna\"}\nT-testi tulemuste esitamisel peab kirjas olema: mõlema grupi keskmine, nende erinevus,\nusaldusvahemik, t-väärtus, vabadusastmed, p-väärtus ja **sisuline järeldus**.\n\nKui erinevus **on** statistiliselt oluline:\n\n**Meeste keskmine vasak-parem enesepaigutus oli 5.86 ja naiste oma 5.51, erinevus seega 0.35 punkti skaalal 0–10. Kahe grupi keskmiste võrdlemiseks läbi viidud t-test näitas, et erinevus on statistiliselt oluline (t = 3.07, df = 1049.6, p = 0.0022; 95% usaldusvahemik 0.13 kuni 0.57). Eesti mehed paigutavad end seega keskmiselt veidi parempoolsemalt kui naised, kuigi erinevus on sisuliselt väike.**\n\nKui erinevus **ei ole** statistiliselt oluline:\n\n**Meeste keskmine suhtumine sisserändesse oli 0.005 ja naiste oma -0.004 faktorskoori skaalal. T-test ei näidanud statistiliselt olulist erinevust (t = 0.18, df = 1111.1, p = 0.86; 95% usaldusvahemik -0.096 kuni 0.115). Andmed ei anna alust väita, et Eesti meeste ja naiste suhtumine sisserändesse erineks.**\n\nKaks asja, mida **mitte** kirjutada:\n\n* **\"erinevust ei ole\"** — õige on \"andmed ei anna alust väita, et erinevus oleks\".\n  Erinevus võib olla olemas, aga meie valim on liiga väike, et teda tuvastada.\n* **\"p = 0,000\"** — kirjuta `p < 0,001`. Tõenäosus ei ole kunagi täpselt null.\n:::\n\n## Harjutused\n\n::: {.harjutus}\n**1. Ühe grupi test.** Testi, kas Eesti elanike keskmine rahulolu demokraatiaga erineb skaala keskpunktist 5. Sõnasta null- ja alternatiivhüpotees enne testi tegemist.\n\n**2. Kahe grupi test.** Kas poliitikast huvitatud ja mittehuvitatud inimeste usaldus poliitikute vastu erineb? Tee t-test ja kirjuta tulemus välja korrektses vormis.\n\n**3. Veel üks võrdlus.** Kas kõrgharidusega ja ilma kõrghariduseta inimeste suhtumine sisserändesse erineb? (Kasuta harjutuses 4.1 tehtud binaarset muutujat.)\n\n**4. Sisuline olulisus.** Vali üks eelmistest testidest, kus tulemus oli statistiliselt oluline. Kui suur erinevus tegelikult oli? Kas sa peaksid teda sisuliselt oluliseks? Põhjenda.\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}