{
  "hash": "6bde6080e285bcda4906374710f1af56",
  "result": {
    "engine": "knitr",
    "markdown": "# 4. Andmete ettevalmistus II\n\nEelmises praktikumis vaatasime, mis meie andmestikus on. Nüüd teeme temast\nanalüüsivalmis andmestiku: valime muutujad, kodeerime nad ümber, ehitame mitmest\nküsimusest uued muutujad ja salvestame tulemuse.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(haven)\nlibrary(dplyr)\n\nee_raw <- read_sav(\"data/ess11_ee_raw.sav\")\n```\n:::\n\n\n## Muutujate valimine\n\n426 muutujast läheb meile vaja umbes kolmekümmend. Valime nad välja funktsiooniga\n`select()`, millega tegime tutvust eelmises praktikumis.\n\nKirjutame valiku teemade kaupa ja kommenteerime ära, mis on mis. See ei ole\nilutsemine — kolme kuu pärast ei mäleta sa ise ka, miks just need muutujad valitud said.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nee <- ee_raw |>\n  select(\n    idno, pspwght, anweight,\n    # demograafia\n    agea, gndr, eisced, hinctnta, domicil,\n    # poliitika\n    lrscale, polintr, vote, prtvtiee, stfdem, ppltrst,\n    # suhtumine sisserändesse (indeksi koostisosad)\n    imbgeco, imueclt, imwbcnt,\n    # institutsionaalne usaldus (indeksi koostisosad)\n    trstprl, trstlgl, trstplc, trstplt, trstprt, trstep, trstun,\n    # tervis\n    health\n  )\n\ndim(ee)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## [1] 1293   25\n```\n\n\n:::\n:::\n\n\n## Valimisosalus: kategooria, mis ei ole puuduv väärtus\n\nEelmises praktikumis leidsime, et muutujal `vote` on kolm kategooriat ja kolmas neist —\n\"ei olnud hääleõiguslik\", 111 inimest — tuleb R-i sisse päris arvuna 3.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(zap_labels(ee$vote), useNA = \"ifany\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## \n##    1    2    3 <NA> \n##  871  304  111    7\n```\n\n\n:::\n:::\n\n\nTeeme sellest korraliku muutuja. Meil on vaja kahte asja korraga:\n\n1. kategooria 3 peab muutuma puuduvaks väärtuseks;\n2. kodeering 1/2 peab muutuma kodeeringuks 1/0, sest logistiline regressioon\n   (praktikum 5) tahab sõltuvat tunnust just sellisel kujul.\n\nSelleks on funktsioon `case_when()`. Ta on **mitmene tingimuslause**: iga rida tema sees\non kujul `tingimus ~ väärtus` ning neid loetakse ülevalt alla — esimene sobiv tingimus\nannab tulemuse. Argument `.default` määrab, mis saab kõigist ülejäänutest.\n\n`NA_real_` on puuduv väärtus arvulise muutuja jaoks. R-is on igal andmetüübil oma\n`NA`-variant (`NA_character_` tekstile, `NA_real_` arvudele) ja `case_when()` nõuab, et\nkõik harud annaksid sama tüüpi väärtuse.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nee <- ee |>\n  mutate(\n    valis = case_when(\n      as.numeric(vote) == 1 ~ 1,   # jah, käisin valimas\n      as.numeric(vote) == 2 ~ 0,   # ei käinud\n      .default = NA_real_          # 3 = ei olnud hääleõiguslik, ja NA-d\n    )\n  )\n\ntable(ee$valis, useNA = \"ifany\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## \n##    0    1 <NA> \n##  304  871  118\n```\n\n\n:::\n:::\n\n\n871 valis, 304 ei valinud, 118 on puuduvad (111 hääleõiguseta + 7 vastamata).\n\n> Kontrolli alati ümber kodeerimise järel tabeliga, kas tulemus on selline, nagu sa\n> ootasid. Arvud peavad kokku minema. Kui nad ei lähe, siis on tingimustes viga — ja\n> `case_when()` ei ütle sulle seda ise.\n\n## Mitmest küsimusest üks muutuja\n\n### Miks küsitluses ei ole päris pidevaid muutujaid\n\nPeaaegu kõik meid huvitavad nähtused — hoiakud, väärtused, usaldus — ei ole\notseselt mõõdetavad. Me küsime nende kohta küsimusi ja vastaja valib mõne vastuse skaalal, millel võib olla neli või seitse või üksteist (või mõni muu arv) kategooriat.\n\nIga selline üksik küsimus on **jäme ja mürane mõõdik**. Jäme, sest kategooriaid on vähe ja\nvastaja tegelik hoiak jääb kuhugi kahe astme vahele. Mürane, sest vastust mõjutab\nküsimuse sõnastus, vastaja tuju ja see, mida temalt eelmisena küsiti.\n\nLahendus on küsida sama asja kohta **mitu küsimust** ja need kokku panna. Nii saame\npeenema skaala ja osa juhuslikust mürast taandub välja.\n\n### Miks mitte lihtsalt keskmine\n\nKõige lihtsam viis kokku panemiseks oleks võtta küsimuste keskmine. See aga eeldab, et\nkõik küsimused mõõdavad uuritavat nähtust **ühtviisi hästi**, mis üldiselt ei ole tõsi.\nMõni küsimus tabab asja täpsemalt, mõni on kaudsem.\n\nSeetõttu kasutame **faktoranalüüsi**. Selle mõte on järgmine: kui mitu küsimust on\nomavahel seotud, siis on selle taga ilmselt üks ühine nähtus, mida nad kõik mõõdavad.\nSee ühine nähtus ongi **faktor**. Faktoranalüüs leiab ta üles ja annab meile kaks asja:\n\n* **faktorlaadungid** — kui tugevalt iga küsimus selle ühise nähtusega seotud on. Mida\n  suurem laadung, seda paremini see küsimus nähtust mõõdab ja seda rohkem ta\n  lõpptulemuses kaalub;\n* **faktorskoorid** — iga vastaja väärtus sellel leitud ühisel nähtusel. Just see ongi\n  meie uus muutuja.\n\n> Rohkem me faktoranalüüsi sellel kursusel ei käsitle — see on omaette teema omaette\n> kursusel. Meile piisab teadmisest, et ta annab paremini kaalutud kokkuvõtte muutujatest, mis mõõdavad sama asja, kui lihtne\n> keskmine.\n\n### Suhtumine sisserändesse\n\nKolm küsimust, kõik skaalal 0–10:\n\n| Muutuja | 0 | 10 |\n|---------|---|-----|\n| `imbgeco` | halb majandusele | hea majandusele |\n| `imueclt` | kahjustab kultuuri | rikastab kultuuri |\n| `imwbcnt` | halvem koht elamiseks | parem koht elamiseks |\n\nEnne kokku panemist tuleb kaks asja üle kontrollida: kas küsimused on **omavahel seotud** ja kas nad on **samas suunas**. Mõlemad on siin täidetud — küsimused on tugevalt seotud ja kõik käivad samas suunas, nii et suurem väärtus tähendab positiivsemat suhtumist.\n\n> Kuidas seda kontrollida, vaatame praktikumis 8, kui jõuame korrelatsiooni juurde. Praegu võta see teadmiseks.\n\nNüüd faktoranalüüs funktsiooniga `factanal()`. Argumendid:\n\n* esimene argument — andmetabel ainult nende küsimustega, mida analüüsida;\n* `factors` — mitu ühist nähtust otsida. Meil on üks;\n* `scores` — väärtusega `\"regression\"` palume arvutada iga vastaja faktorskoori.\n\nEnne seda tuleb andmed ette valmistada. `factanal()` tahab tavalisi arvulisi muutujaid ja ei oska puuduvate väärtustega midagi peale hakata.\n\n* `lapply()` rakendab funktsiooni igale andmetabeli veerule eraldi. Siin: tee igast veerust `as.numeric()`. Ta sarnaneb funktsioonile `sapply()`, mida kasutasime eelmises praktikumis, kuid annab tulemuse nimekirjana.\n* `as.data.frame()` teeb saadud nimekirjast tagasi andmetabeli.\n* `complete.cases()` annab `TRUE` nende ridade kohta, kus ühtegi puuduvat väärtust ei ole.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nranne_kysimused <- c(\"imbgeco\", \"imueclt\", \"imwbcnt\")\n\nranne_veerud <- lapply(ee[ranne_kysimused], as.numeric)\nranne_andmed <- as.data.frame(ranne_veerud)\nranne_terved <- complete.cases(ranne_andmed)\n\nranne_fa <- factanal(\n  ranne_andmed[ranne_terved, ],\n  factors = 1,\n  scores = \"regression\"\n)\n\nranne_fa$loadings\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## \n## Loadings:\n##         Factor1\n## imbgeco 0.705  \n## imueclt 0.781  \n## imwbcnt 0.871  \n## \n##                Factor1\n## SS loadings      1.867\n## Proportion Var   0.622\n```\n\n\n:::\n:::\n\n\nLaadungid on kõik tugevad ja positiivsed. Kõige rohkem kaalub kolmas küsimus (kas sisserändajad teevad Eesti paremaks või halvemaks kohaks), kõige vähem esimene (mõju majandusele).\n\nRida `Proportion Var` ütleb, kui suure osa kolme küsimuse koguvarieeruvusest see üks ühine nähtus ära seletab.\n\n### Faktorskooride tagasi panemine\n\nNüüd paneme skoorid andmetabelisse. Siin on üks konks, mis kipub ununema: **kuna faktoranalüüs kasutas ainult osa ridadest, ei saa me skoore lihtsalt veeruks panna** — nad ei satuks õigete inimeste kohale.\n\nSeega teeme esmalt tühja muutuja ja täidame ainult need read, mille kohta skoor arvutati.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nee$ranne <- NA_real_\nee$ranne[ranne_terved] <- ranne_fa$scores[, 1]\n```\n:::\n\n\nTeine konks: **faktori suund on matemaatiliselt suvaline.** Analüüs ei tea, kumb ots on \"positiivne suhtumine\" — ta leiab ainult telje, mitte selle nime. Seega kontrollime ise üle ja pöörame vajadusel ümber.\n\nSelleks on **tingimuslause** `if () { }`. Ümarsulgudes on tingimus, looksulgudes see, mida teha, kui tingimus on tõene. Kui tingimus on väär, siis ei tehta midagi.\n\n> Erinevus funktsioonidest `if_else()` ja `case_when()`: need kaks töötavad muutuja iga väärtusega eraldi. `if ()` otsustab **ühe korra**, kas tervet plokki üldse käivitada.\n\nSuuna kontrollimiseks kasutame funktsiooni `cor()`, mis mõõdab kahe muutuja seost. Meid huvitab siin ainult **märk**: kui faktorskoor on mõne algse küsimusega negatiivselt seotud, siis on ta tagurpidi ja tuleb ümber pöörata. Argument `use = \"complete.obs\"` ütleb, et arvutada ainult nende vastajate põhjal, kellel mõlemad väärtused olemas on.\n\n> Korrelatsiooni juurde tuleme põhjalikult tagasi praktikumis 8. Praegu on vaja teada ainult üht asja: **positiivne arv tähendab sama suunda, negatiivne vastupidist.**\n\nMiinusmärk arvu ees pöörab kõik väärtused vastasmärgiliseks.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nimwbcnt_arvuna <- as.numeric(ee$imwbcnt)\nranne_suund <- cor(ee$ranne, imwbcnt_arvuna, use = \"complete.obs\")\n\nif (ranne_suund < 0) {\n  ee$ranne <- -ee$ranne\n}\n\nsummary(ee$ranne)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n##     Min.  1st Qu.   Median     Mean  3rd Qu.     Max.      NAs \n## -2.37418 -0.53874  0.02006  0.00000  0.59555  2.30370       85\n```\n\n\n:::\n:::\n\n\nSuurem väärtus tähendab nüüd positiivsemat suhtumist sisserändesse.\n\n::: {.arutelu}\n**Arutelu.** Faktorskoori keskmine on null ja standardhälve umbes üks. **Mida tähendab siis see, kui inimese väärtus on −1,5?** Ja kas seda muutujat saab tõlgendada nii nagu algseid küsimusi skaalal 0–10?\n:::\n\n### Institutsionaalne usaldus\n\nTeeme sama asja teise näite peal. ESS-is küsitakse usalduse kohta seitset küsimust, kõik skaalal 0–10, kus 0 tähendab \"ei usalda üldse\" ja 10 \"usaldan täielikult\":\n\n| Muutuja | Mida usaldatakse |\n|---|---|\n| `trstprl` | Riigikogu |\n| `trstlgl` | õigussüsteem |\n| `trstplc` | politsei |\n| `trstplt` | poliitikud |\n| `trstprt` | erakonnad |\n| `trstep` | Euroopa Parlament |\n| `trstun` | ÜRO |\n\nKa need on eelnevalt üle kontrollitud: kõik samas suunas ja omavahel tugevalt seotud.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nusaldus_kysimused <- c(\n  \"trstprl\", \"trstlgl\", \"trstplc\",\n  \"trstplt\", \"trstprt\", \"trstep\", \"trstun\"\n)\n\nusaldus_veerud <- lapply(ee[usaldus_kysimused], as.numeric)\nusaldus_andmed <- as.data.frame(usaldus_veerud)\nusaldus_terved <- complete.cases(usaldus_andmed)\n\nusaldus_fa <- factanal(\n  usaldus_andmed[usaldus_terved, ],\n  factors = 1,\n  scores = \"regression\"\n)\n\nusaldus_fa$loadings\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## \n## Loadings:\n##         Factor1\n## trstprl 0.845  \n## trstlgl 0.732  \n## trstplc 0.587  \n## trstplt 0.871  \n## trstprt 0.847  \n## trstep  0.854  \n## trstun  0.700  \n## \n##                Factor1\n## SS loadings      4.292\n## Proportion Var   0.613\n```\n\n\n:::\n:::\n\n\nKõik seitse laadungit on positiivsed ja tugevad. Kõige nõrgemalt laadub usaldus politsei vastu — inimesed, kes ei usalda poliitikuid, usaldavad politseid sageli siiski.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nee$usaldus <- NA_real_\nee$usaldus[usaldus_terved] <- usaldus_fa$scores[, 1]\n\ntrstplt_arvuna <- as.numeric(ee$trstplt)\nusaldus_suund <- cor(ee$usaldus, trstplt_arvuna, use = \"complete.obs\")\n\nif (usaldus_suund < 0) {\n  ee$usaldus <- -ee$usaldus\n}\n\nsummary(ee$usaldus)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n##     Min.  1st Qu.   Median     Mean  3rd Qu.     Max.      NAs \n## -2.12429 -0.67805  0.08064  0.00000  0.76016  2.57866      176\n```\n\n\n:::\n:::\n\n\n> **Pane tähele, et kood on mõlema indeksi puhul täpselt sama kujuga.** Muutuvad ainult muutujate nimed. See ongi üks põhjus, miks tasub kood kirjutada selgete sammudena — teist korda on ta juba valmis muster, mida saab kohandada.\n\n\n## Väikeste kategooriate kokku panemine\n\nVaatame erakondlikku eelistust. Funktsioon `as_factor()` teeb `haven_labelled`\nmuutujast faktori, kasutades kategooriate nimedena silte.\n\nFunktsioon `sort()` järjestab tabeli; argument `decreasing = TRUE` teeb seda suuremast\nväiksemani.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nerakond_kogu <- as_factor(ee$prtvtiee)\n\nsort(table(erakond_kogu), decreasing = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## erakond_kogu\n##              Eesti Reformierakond                    Isamaa Erakond \n##                               231                               125 \n##                         Eesti 200      Sotsiaaldemokraatlik Erakond \n##                               117                               104 \n## Eesti Konservatiivne Rahvaerakond                 Eesti Keskerakond \n##                               104                                93 \n##                      Parempoolsed                  Üksikkandidaadid \n##                                21                                10 \n##        Erakond Eestimaa Rohelised                             Other \n##                                 5                                 3 \n##                 Eesti Vabaerakond    Eestimaa Ühendatud Vasakpartei \n##                                 0                                 0 \n##                    Not applicable                           Refusal \n##                                 0                                 0 \n##                        Don't know                         No answer \n##                                 0                                 0\n```\n\n\n:::\n:::\n\n\nKuus erakonda on korraliku suurusega — 93 kuni 231 vastajat. Ülejäänud on üksikud\njuhtumid: 21, 10, 5, 3.\n\n**Viie vastajaga grupi kohta ei saa statistiliselt midagi öelda.** Iga arv, mille sa\nselle grupi kohta arvutad, sõltub täielikult sellest, kes need viis inimest juhtumisi\nolid. Seega paneme nad kokku kategooriasse \"muu\".\n\nÜhtlasi kasutame **lühikesi nimetusi**. Pikad erakonnanimed ei mahu tabelitesse ega joonistele ära ning lõhuvad vormistuse. Lühendame kohe siin, mitte hiljem iga joonise juures eraldi.\n\nKirjutame iga sammu eraldi reale, et oleks näha, mis järjekorras asjad toimuvad.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 1. samm. Teeme siltidest faktori ja siis tekstilise muutuja, et nendega\n#    saaks võrrelda.\nerakond_faktorina <- as_factor(ee$prtvtiee)\nerakond_tekstina <- as.character(erakond_faktorina)\n\n# 2. samm. case_when() annab igale suuremale erakonnale lühikese nime ja\n#    kõigile ülejäänutele \"Muu\". Puuduvad väärtused peavad puuduvaks jääma,\n#    mitte muutuma kategooriaks \"Muu\" -- seetõttu on neil oma rida.\nerakond_lyhike <- case_when(\n  erakond_tekstina == \"Eesti Reformierakond\" ~ \"Reform\",\n  erakond_tekstina == \"Isamaa Erakond\" ~ \"Isamaa\",\n  erakond_tekstina == \"Eesti 200\" ~ \"E200\",\n  erakond_tekstina == \"Sotsiaaldemokraatlik Erakond\" ~ \"SDE\",\n  erakond_tekstina == \"Eesti Konservatiivne Rahvaerakond\" ~ \"EKRE\",\n  erakond_tekstina == \"Eesti Keskerakond\" ~ \"Kesk\",\n  is.na(erakond_tekstina) ~ NA_character_,\n  .default = \"Muu\"\n)\n\n# 3. samm. factor() teeb tekstist kategoorilise muutuja. Argument levels\n#    määrab kategooriate JÄRJEKORRA.\nee$erakond <- factor(\n  erakond_lyhike,\n  levels = c(\"Reform\", \"Isamaa\", \"E200\", \"SDE\", \"EKRE\", \"Kesk\", \"Muu\")\n)\n\ntable(ee$erakond, useNA = \"ifany\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## \n## Reform Isamaa   E200    SDE   EKRE   Kesk    Muu   <NA> \n##    231    125    117    104    104     93     39    480\n```\n\n\n:::\n:::\n\n\n> **Kategooriate järjekord on oluline.** Esimene kategooria jääb regressioonimudelis\n> **referentskategooriaks** — selleks, mille suhtes kõiki teisi võrreldakse (praktikum\n> 11). Joonistel kuvatakse kategooriad samuti selles järjekorras. Seega tasub järjekord\n> läbi mõelda juba siin, mitte hiljem iga joonise juures eraldi.\n\n## Siltide tõlkimine\n\nESS-i sildid on inglise keeles. Kuna kogu meie töö on eesti keeles ja need sildid\nlähevad hiljem otse joonistele ja tabelitesse, on kõige mõistlikum nad **kohe siin ära\ntõlkida.** Nii ei pea seda tegema iga joonise juures uuesti.\n\nFunktsioon `levels()` näitab faktori kategooriaid nende järjekorras. Sama funktsiooniga\nsaab neid ka **asendada**, kui kirjutada ta võrdusmärgist vasakule.\n\n> **Kontrolli alati enne asendamist, mis järjekorras kategooriad on.** Kui sa selle\n> valesti arvad, siis satuvad sildid vale kategooria juurde — ja mitte miski ei anna\n> sulle veateadet. Sinu joonisel on lihtsalt vale info.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlevels(as_factor(ee$gndr))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## [1] \"Male\"      \"Female\"    \"No answer\"\n```\n\n\n:::\n\n```{.r .cell-code}\nlevels(as_factor(ee$domicil))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## [1] \"A big city\"                       \"Suburbs or outskirts of big city\"\n## [3] \"Town or small city\"               \"Country village\"                 \n## [5] \"Farm or home in countryside\"      \"Refusal\"                         \n## [7] \"Don't know\"                       \"No answer\"\n```\n\n\n:::\n\n```{.r .cell-code}\nlevels(as_factor(ee$health))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## [1] \"Very good\"  \"Good\"       \"Fair\"       \"Bad\"        \"Very bad\"  \n## [6] \"Refusal\"    \"Don't know\" \"No answer\"\n```\n\n\n:::\n:::\n\n\nFunktsioon `droplevels()` viskab välja kategooriad, mida andmetes tegelikult ei esine —\nsiltides on ka \"Refusal\" ja \"Don't know\", aga ühelgi vastajal neid väärtusi ei ole.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nee$sugu <- droplevels(as_factor(ee$gndr))\nlevels(ee$sugu) <- c(\"mees\", \"naine\")\n\nee$elukoht <- droplevels(as_factor(ee$domicil))\nlevels(ee$elukoht) <- c(\n  \"suurlinn\",\n  \"äärelinn\",\n  \"väikelinn\",\n  \"maa-asula\",\n  \"maakodu\"\n)\n\n\ntable(ee$elukoht)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## \n##  suurlinn  äärelinn väikelinn maa-asula   maakodu \n##       435       133       385       249        89\n```\n\n\n:::\n:::\n\n\n## Ülejäänud muutujad\n\nPidevad ja järjestatud muutujad teeme arvulisteks ja anname neile eestikeelsed nimed.\n\nMuutuja `eisced` on haridustase skaalal 1–7. ESS-i failis on ka koodid 0 (\"ei saa\nharmoniseerida\") ja 55 (\"muu\"), mis **ei ole** märgitud puuduvateks väärtusteks. Eesti\nandmetes neid ei esine — aga me kontrollime seda, mitte ei eelda.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(zap_labels(ee$eisced), useNA = \"ifany\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## \n##    1    2    3    4    5    6    7 <NA> \n##   23  138   35  381  219  204  291    2\n```\n\n\n:::\n:::\n\n\nAinult väärtused 1–7. Korras.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nee <- ee |>\n  mutate(\n    vanus = as.numeric(agea),\n    haridus = as.numeric(eisced),\n    sissetulek = as.numeric(hinctnta),\n    vasak_parem = as.numeric(lrscale),\n    usaldus_pol = as.numeric(trstplt),\n    usaldus_rii = as.numeric(trstprl),\n    usaldus_inim = as.numeric(ppltrst),\n    rahulolu_dem = as.numeric(stfdem),\n    # tervis: ESS-is 1 = väga hea ... 5 = väga halb. Pöörame ümber, et suurem\n    # väärtus tähendaks paremat tervist. Viis kategooriat, seega võime teda\n    # käsitleda pidevana.\n    tervis = 6 - as.numeric(health),\n    # huvi poliitika vastu: ESS-is 1 = väga huvitatud ... 4 = üldse mitte.\n    # NELI kategooriat on pideva muutuja jaoks liiga vähe, seega teeme temast\n    # binaarse muutuja.\n    huvi_pol = case_when(\n      as.numeric(polintr) %in% c(1, 2) ~ 1,\n      as.numeric(polintr) %in% c(3, 4) ~ 0,\n      .default = NA_real_\n    )\n  )\n```\n:::\n\n\n> Pane tähele viimast rida. `polintr` on **kolmas** tagurpidi muutuja, mis meil ette\n> tuli. Küsitlusandmetes on see täiesti tavaline. Kontrolli iga järjestatud muutuja\n> puhul, kummas otsas on \"rohkem\".\n\n## Analüüsivalmis andmestik\n\nVõtame lõpuks välja ainult need muutujad, mida päriselt kasutame.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata <- ee |>\n  select(\n    idno, pspwght, anweight,\n    vanus, sugu, haridus, sissetulek, elukoht,\n    vasak_parem, huvi_pol, valis, erakond,\n    usaldus_pol, usaldus_rii, usaldus_inim, rahulolu_dem,\n    ranne, usaldus, tervis\n  )\n\nstr(data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## tibble [1,293 × 19] (S3: tbl_df/tbl/data.frame)\n##  $ idno        : num [1:1293] 50030 50069 50119 50137 50147 ...\n##   ..- attr(*, \"label\")= chr \"Respondent's identification number\"\n##   ..- attr(*, \"format.spss\")= chr \"F8.2\"\n##  $ pspwght     : num [1:1293] 1.086 0.776 0.846 0.941 2.126 ...\n##   ..- attr(*, \"label\")= chr \"Post-stratification weight including design weight\"\n##   ..- attr(*, \"format.spss\")= chr \"F8.2\"\n##  $ anweight    : num [1:1293] 0.0959 0.0686 0.0747 0.0831 0.1877 ...\n##   ..- attr(*, \"label\")= chr \"Analysis weight\"\n##   ..- attr(*, \"format.spss\")= chr \"F8.2\"\n##  $ vanus       : num [1:1293] 36 82 69 69 69 51 16 41 75 17 ...\n##  $ sugu        : Factor w/ 2 levels \"mees\",\"naine\": 1 2 1 2 2 1 2 2 2 2 ...\n##  $ haridus     : num [1:1293] 4 7 7 3 2 3 1 5 4 2 ...\n##  $ sissetulek  : num [1:1293] 9 3 7 5 6 NA 1 7 4 4 ...\n##  $ elukoht     : Factor w/ 5 levels \"suurlinn\",\"äärelinn\",..: 3 1 3 4 1 4 2 4 3 4 ...\n##  $ vasak_parem : num [1:1293] 5 5 8 NA NA 5 5 5 NA 5 ...\n##  $ huvi_pol    : num [1:1293] 1 1 1 1 0 1 0 0 0 1 ...\n##  $ valis       : num [1:1293] 1 1 1 1 NA 1 NA 1 1 NA ...\n##  $ erakond     : Factor w/ 7 levels \"Reform\",\"Isamaa\",..: 5 4 1 6 NA 1 NA 1 6 NA ...\n##  $ usaldus_pol : num [1:1293] 0 8 8 5 4 5 4 7 2 4 ...\n##  $ usaldus_rii : num [1:1293] 0 6 8 5 3 5 5 9 8 5 ...\n##  $ usaldus_inim: num [1:1293] 1 7 8 10 5 3 4 7 7 5 ...\n##  $ rahulolu_dem: num [1:1293] 5 8 7 7 4 9 6 8 8 7 ...\n##  $ ranne       : num [1:1293] -2.2837 -0.0352 1.1169 -0.666 0.0909 ...\n##  $ usaldus     : num [1:1293] -1.9 1.42 1.12 NA NA ...\n##  $ tervis      : num [1:1293] 3 4 4 2 3 3 2 4 3 4 ...\n##  - attr(*, \"label\")= chr \"ESS11 edition 4.2, Eesti\"\n```\n\n\n:::\n:::\n\n\nJa vaatame kokkuvõtte. Funktsioon `summary()` töötab ka terve andmetabeli peal korraga.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n##       idno          pspwght          anweight           vanus          sugu    \n##  Min.   :50030   Min.   :0.7718   Min.   :0.06816   Min.   :15.00   mees :577  \n##  1st Qu.:58499   1st Qu.:0.7784   1st Qu.:0.06875   1st Qu.:37.00   naine:716  \n##  Median :67095   Median :0.9030   Median :0.07975   Median :50.00              \n##  Mean   :67662   Mean   :1.0000   Mean   :0.08832   Mean   :50.07              \n##  3rd Qu.:77009   3rd Qu.:1.1380   3rd Qu.:0.10051   3rd Qu.:64.00              \n##  Max.   :86448   Max.   :2.1313   Max.   :0.18824   Max.   :90.00              \n##                                                     NAs    :7                  \n##     haridus        sissetulek          elukoht     vasak_parem    \n##  Min.   :1.000   Min.   : 1.000   suurlinn :435   Min.   : 0.000  \n##  1st Qu.:4.000   1st Qu.: 4.000   äärelinn :133   1st Qu.: 5.000  \n##  Median :5.000   Median : 6.000   väikelinn:385   Median : 5.000  \n##  Mean   :4.868   Mean   : 6.298   maa-asula:249   Mean   : 5.672  \n##  3rd Qu.:6.000   3rd Qu.: 9.000   maakodu  : 89   3rd Qu.: 7.000  \n##  Max.   :7.000   Max.   :10.000   NAs      :  2   Max.   :10.000  \n##  NAs    :2       NAs    :114                      NAs    :185     \n##     huvi_pol          valis           erakond     usaldus_pol    \n##  Min.   :0.0000   Min.   :0.0000   Reform :231   Min.   : 0.000  \n##  1st Qu.:0.0000   1st Qu.:0.0000   Isamaa :125   1st Qu.: 2.000  \n##  Median :0.0000   Median :1.0000   E200   :117   Median : 3.000  \n##  Mean   :0.4554   Mean   :0.7413   SDE    :104   Mean   : 3.443  \n##  3rd Qu.:1.0000   3rd Qu.:1.0000   EKRE   :104   3rd Qu.: 5.000  \n##  Max.   :1.0000   Max.   :1.0000   (Other):132   Max.   :10.000  \n##  NAs    :4        NAs    :118      NAs    :480   NAs    :16      \n##   usaldus_rii      usaldus_inim     rahulolu_dem        ranne         \n##  Min.   : 0.000   Min.   : 0.000   Min.   : 0.000   Min.   :-2.37418  \n##  1st Qu.: 3.000   1st Qu.: 5.000   1st Qu.: 3.000   1st Qu.:-0.53874  \n##  Median : 5.000   Median : 6.000   Median : 5.000   Median : 0.02006  \n##  Mean   : 4.579   Mean   : 5.692   Mean   : 5.108   Mean   : 0.00000  \n##  3rd Qu.: 7.000   3rd Qu.: 7.000   3rd Qu.: 7.000   3rd Qu.: 0.59555  \n##  Max.   :10.000   Max.   :10.000   Max.   :10.000   Max.   : 2.30370  \n##  NAs    :22       NAs    :2        NAs    :66       NAs    :85        \n##     usaldus             tervis    \n##  Min.   :-2.12429   Min.   :1.00  \n##  1st Qu.:-0.67805   1st Qu.:3.00  \n##  Median : 0.08064   Median :4.00  \n##  Mean   : 0.00000   Mean   :3.59  \n##  3rd Qu.: 0.76016   3rd Qu.:4.00  \n##  Max.   : 2.57866   Max.   :5.00  \n##  NAs    :176        NAs    :1\n```\n\n\n:::\n:::\n\n\nKui palju juhtumeid on iga muutuja puhul tegelikult olemas?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsapply(data, function(x) sum(!is.na(x)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n##         idno      pspwght     anweight        vanus         sugu      haridus \n##         1293         1293         1293         1286         1293         1291 \n##   sissetulek      elukoht  vasak_parem     huvi_pol        valis      erakond \n##         1179         1291         1108         1289         1175          813 \n##  usaldus_pol  usaldus_rii usaldus_inim rahulolu_dem        ranne      usaldus \n##         1277         1271         1291         1227         1208         1117 \n##       tervis \n##         1292\n```\n\n\n:::\n:::\n\n\n> Hüüumärk `!` tähendab R-is \"mitte\". `!is.na(x)` tähendab seega \"ei ole puuduv\" ehk\n> \"on olemas\".\n\nSalvestame. Funktsioon `save()` salvestab objekti R-i enda formaadis; argument `file`\nmäärab faili nime. Hiljem saab selle tagasi laadida funktsiooniga `load()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsave(data, file = \"data/ess11_ee_clean.rdata\")\n```\n:::\n\n\n## Kokkuvõte\n\nObjekt `data` on see, millega me alates järgmisest praktikumist töötame. Kogu see töö on\nkoos ühes failis: `R/ettevalmistus.R`.\n\nMida me kahes praktikumis tegime:\n\n| Samm | Miks |\n|------|------|\n| valisime muutujad | 426-st läks vaja 19 |\n| kodeerisime `vote` ümber | üks kategooria ei olnud päris vastus |\n| ehitasime kaks indeksit | üksik küsimus on liiga jäme mõõdik |\n| tegime poliitikahuvist binaarse muutuja | neli kategooriat on pidevaks liiga vähe |\n| pöörasime kaks muutujat ümber | skaala oli tagurpidi |\n| panime väiksed erakonnad kokku | viie vastajaga grupist ei saa järeldusi teha |\n| tõlkisime sildid | joonised ja tabelid tulevad eesti keeles |\n\n> **See ongi see osa tööst, mida keegi ei näe ja mida kõik alahindavad.** Sinu\n> uurimustöös ei ole seda peatükki. Aga kui sa selle töö tegemata jätad või valesti\n> teed, siis on kõik ülejäänud peatükid valed.\n\n## Harjutused\n\n::: {.harjutus}\n**1. Ümber kodeerimine.** Tee muutujast `haridus` binaarne muutuja, mis näitab, kas inimesel on kõrgharidus (`haridus` on 6 või 7) või mitte. Kontrolli tabeliga, kas arvud lähevad kokku.\n\n**2. Kategooriate kokku panemine.** Tee muutujast `elukoht` uus muutuja, kus on ainult kaks kategooriat: linn (suurlinn, äärelinn, väikelinn) ja maa (maa-asula, maakodu).\n\n**3. Faktori järjekord.** Muuda muutuja `erakond` tasemete järjekorda nii, et referentskategooriaks jääks EKRE. Kontrolli funktsiooniga `levels()`.\n\n**4. Oma indeks.** ESS-is on rahulolu mõõtvad muutujad `stfeco` (majandus), `stfgov` (valitsus), `stfedu` (haridus) ja `stfhlth` (tervishoid), kõik skaalal 0–10. Tee neist faktoranalüüsi abil üks muutuja. Millised laadungid tulevad? Ära unusta suunda kontrollida.\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}