{
  "hash": "2ee72d0c1bd69a2616d97803541c7941",
  "result": {
    "engine": "knitr",
    "markdown": "# 11. Logistiline regressioon\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\nlibrary(ggplot2)\nlibrary(modelsummary)\nlibrary(ggeffects)\nlibrary(pscl)\nload(\"data/ess11_ee_clean.rdata\")\n```\n:::\n\n\nViimane teema. Siiani on meie sõltuv muutuja olnud alati pidev. Aga väga sageli ei ole ta seda — käis valimas või ei käinud, töötab või ei tööta, jäi haigeks või ei jäänud.\n\nSelliste sõltuvate muutujate jaoks on **logistiline regressioon**.\n\n## Miks tavaline regressioon ei sobi\n\nMeie muutuja `valis` on kodeeritud 0 ja 1 — täpselt nii, nagu me ta praktikumis 4 ette\nvalmistasime.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(data$valis, useNA = \"ifany\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## \n##    0    1 <NA> \n##  304  871  118\n```\n\n\n:::\n:::\n\n\nMis juhtuks, kui me teeksime tavalise regressiooni? Sõltuva muutuja väärtused on 0 ja 1, seega ennustaks mudel midagi nende vahel — ja seda võiks tõlgendada tõenäosusena.\n\nProovime.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhalb <- lm(valis ~ huvi_pol + vanus + haridus, data = data)\n\nennustused <- predict(halb)\n\nrange(ennustused)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## [1] 0.3236606 1.0408087\n```\n\n\n:::\n:::\n\n\n\n\n**Vaata ülemist otsa.** Mudel ennustab suurimaks väärtuseks 1.041. Tõenäosus ei saa olla suurem kui 1 — see on võimatu.\n\nJa see ei ole üksikjuhtum. Loeme kokku, mitme inimese kohta mudel võimatu ennustuse annab:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(ennustused > 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## [1] 35\n```\n\n\n:::\n:::\n\n\n35 inimest. Vaatame ka pilti.\n\n\n::: {.cell}\n\n```{.r .cell-code}\njoonise_andmed <- data.frame(ennustus = ennustused)\n\nggplot(joonise_andmed, aes(x = ennustus)) +\n  geom_histogram(bins = 30, fill = \"dodgerblue3\", color = \"white\") +\n  geom_vline(xintercept = 1, color = \"firebrick3\", linewidth = 1) +\n  labs(\n    x = \"mudeli ennustatud tõenäosus\",\n    y = \"vastajate arv\",\n    title = \"Tavaline regressioon ennustab võimatuid tõenäosusi\"\n  ) +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](11-logistiline-regressioon_files/figure-html/halb-mudel-joonis-1.png){width=672}\n:::\n:::\n\n\nPunane joon on tõenäosuse ülempiir. Osa ennustusi jääb sellest paremale.\n\nProbleem on põhimõtteline. **Sirge joon läheb lõputult üles ja alla, aga tõenäosus on piiritletud nulli ja ühe vahele.** Sirge ei oska kuskil peatuda. Meil on vaja midagi, mis otstes ära kõverduks — lameneks, kui läheneb nullile või ühele.\n\n::: {.arutelu}\n**Arutelu.** Mudel ennustas 35 inimese kohta tõenäosuse, mis on üle ühe. **Miks on see tõsisem probleem kui lihtsalt \"mõned arvud on veidi valed\"?** Mõtle sellele, mida sa nende ennustustega peale hakkaksid.\n:::\n\n## Tõenäosus, šansid ja logit\n\n::: {.panel-tabset}\n\n## Lihtsam seletus\n\nProbleem oli see, et tõenäosus on piiratud nulli ja ühe vahele, aga sirge joon ei ole. Lahendus on **skaala ümber vahetada**: selle asemel et ennustada tõenäosust otse, ennustame midagi muud, mis on tõenäosusega üks-ühele seotud, aga millel piire ei ole.\n\nKuidas see käib? Kahes sammus.\n\n**Esimene samm: tõenäosuse asemel šansid.**\n\nŠansid on igapäevakeelest tuttavad — \"šansid on kolm ühele\". See tähendab: kolm korda tõenäolisem, et juhtub, kui et ei juhtu. Kihlvedudes ja spordis kasutatakse just seda keelt.\n\nŠansid saadakse tõenäosusest lihtsalt: **kui suur on tõenäosus, et juhtub, võrreldes tõenäosusega, et ei juhtu.** Kui tõenäosus on 0,75, siis šansid on kolm ühele. Kui tõenäosus on 0,5, siis šansid on üks ühele.\n\nMis sellega võidetakse? Tõenäosus lõppes ühe juures ära. Šansid **ei lõpe kunagi** — nad kasvavad lõpmatuseni. Ülemine piir on kadunud.\n\nAlumine piir on aga alles: šansid ei saa olla negatiivsed. Nad lähenevad nullile, aga ei jõua sinna kunagi.\n\n**Teine samm: šanssidest logaritm.**\n\nLogaritmi võtmine on tehe, mis teeb ühe kindla asja: **ta venitab nullilähedased arvud laiali ja surub suured arvud kokku.** Arvudest, mis olid nulli ja ühe vahel, saavad negatiivsed arvud; arvudest, mis olid ühest suuremad, saavad positiivsed.\n\nNii kaob ka alumine piir. Tulemus võib olla ükskõik milline arv — nii negatiivne kui positiivne, ilma otsteta.\n\nSeda lõpptulemust nimetatakse **logitiks**. Ta on lihtsalt tõenäosus, mis on kahe sammuga ümber pandud skaalale, millel ei ole otsi. Ja just sellel skaalal saab tavaline sirge joon oma tööd teha.\n\n| | Piirid | Kas sirge sobib? |\n|---|---|---|\n| tõenäosus | 0 kuni 1 | ei |\n| šansid | 0 kuni lõpmatus | ei |\n| **logit** | **piirideta** | **jah** |\n\nKõige olulisem: **see teisendus ei muuda infot, ainult skaalat.** Igast logitist saab tagasi arvutada šansid ja igast šansist tagasi tõenäosuse. Midagi ei lähe kaotsi.\n\n### Mida sa pead teadma tulemuste lugemiseks\n\n**Sina ei pea seda teisendust ise tegema.** R teeb ta ära. Sina pead teadma kolme asja.\n\n**Esiteks: koefitsiendi märk.** See on kõige olulisem ja seda saab lugeda otse tabelist.\n\n* **Positiivne** koefitsient logistilise regressiooni mudelis tähendab, et selle muutuja kasvades **kasvab tõenäosus**, et sõltuv muutuja on 1.\n* **Negatiivne** koefitsient tähendab, et tõenäosus **kahaneb**.\n\n**Teiseks: koefitsiendi arvulist väärtust ei saa otse tõlgendada.** Ta on logiti skaalal ja lause \"logit kasvab 0,8 võrra\" ei tähenda inimese jaoks midagi. Selle jaoks on kaks lahendust, mida allpool vaatame: **šansside suhe** ja **joonis**.\n\n**Kolmandaks: p-väärtust loetakse täpselt sama moodi** nagu tavalises regressioonis. Nullhüpotees on, et koefitsient on null ehk seost ei ole.\n\n> Jäta siinkohal meelde üks asi: **tee joonis.** Ennustatud tõenäosuste joonis ütleb sulle ja su lugejale rohkem kui ükski koefitsient. Sellel joonisel on y-teljel tavaline tõenäosus, mitte logit, ja teda saab lugeda ilma igasuguse teisenduseta.\n\n\n## Täpsem seletus\n\nVaatame, kust logit tuleb. Teekond käib kolmes sammus.\n\n**Samm 1: tõenäosuse asemel šansid.**\n\nŠansid on tõenäosus, et midagi juhtub, jagatud tõenäosusega, et ei juhtu:\n\n$$\\text{šansid} = \\frac{Pr(y=1)}{1 - Pr(y=1)}$$\n\nKui tõenäosus on piiratud 0 ja 1 vahele, siis šansid ulatuvad **nullist lõpmatuseni**.\nNad ei saa olla negatiivsed. Oleme poolel teel.\n\nJoonistame selle. Funktsioon `seq()` teeb arvujada — argument `length.out` ütleb, mitu\narvu jadas olema peab. Funktsioon `geom_line()` joonistab punktide asemel joone.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprob <- seq(0.1, 0.9, length.out = 100)\nodds <- prob / (1 - prob)\n\nsansside_andmed <- data.frame(prob = prob, odds = odds)\n\nggplot(sansside_andmed, aes(prob, odds)) +\n  geom_line(linewidth = 1, color = \"dodgerblue3\") +\n  labs(x = \"tõenäosus\", y = \"šansid\") +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](11-logistiline-regressioon_files/figure-html/sansid-1.png){width=672}\n:::\n:::\n\n\n**Samm 2: šanssidest logaritm.**\n\nLogaritmi võtmine tähendab arvu väljendamist mõne teise arvu astmena. Naturaallogaritmi\nalus on matemaatiline konstant $e$, mille väärtus on umbes 2,71.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlog(1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## [1] 0\n```\n\n\n:::\n\n```{.r .cell-code}\nlog(2.71)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## [1] 0.9969486\n```\n\n\n:::\n\n```{.r .cell-code}\nlog(10, base = 10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## [1] 1\n```\n\n\n:::\n:::\n\n\nLogaritmi saab võtta igast nullist suuremast arvust ja tulemus võib olla **miinus\nlõpmatusest lõpmatuseni**. Arvu 1 logaritm on null; alla ühe on negatiivne, üle ühe\npositiivne.\n\nTäpselt see, mida vaja. Šansside logaritmi nimetatakse **logitiks**.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprob <- seq(0.01, 0.99, length.out = 100)\nodds <- prob / (1 - prob)\n\nlogit_andmed <- data.frame(prob = prob, logit = log(odds))\n\nggplot(logit_andmed, aes(prob, logit)) +\n  geom_line(linewidth = 1, color = \"dodgerblue3\") +\n  labs(x = \"tõenäosus\", y = \"log šansid (logit)\") +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](11-logistiline-regressioon_files/figure-html/logit-joonis-1.png){width=672}\n:::\n:::\n\n\nNüüd on skaala piiramatu ja tavaline lineaarne mudel saab temaga hakkama.\n\n**Samm 3: tagasi.**\n\nLogaritmi vastandtehe on astendamine. Funktsioon `exp()` tõstab $e$ antud astmele.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexp(1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## [1] 2.718282\n```\n\n\n:::\n\n```{.r .cell-code}\nexp(0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## [1] 1\n```\n\n\n:::\n\n```{.r .cell-code}\nexp(-1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## [1] 0.3678794\n```\n\n\n:::\n:::\n\n\nNii saame logitist tagasi šansid ja šanssidest tagasi tõenäosuse:\n\n$$\\text{tõenäosus} = \\frac{\\text{šansid}}{1 + \\text{šansid}}$$\n\n**Kokkuvõttes:** logistiline regressioon ennustab logitit, sest logit käitub nii, nagu\nlineaarne mudel vajab. Tõlgendamiseks teeme tagasitee.\n\n:::\n\n## Mudeli sobitamine\n\nLogistilise regressiooni funktsioon on `glm()` — *generalized linear model*, üldistatud\nlineaarne mudel. Valem kirjutatakse täpselt nagu `lm()` puhul, kuid lisaks tuleb\nargumendiga `family` öelda, millist sõltuva muutuja teisendust kasutada.\n\nVäärtus `\"binomial\"` tähendab, et sõltuv muutuja on binaarne, ja see annab logit-mudeli.\n\nEnnustame, kas inimene käis valimas, tema vanuse, soo, hariduse ja poliitikahuvi\npõhjal.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlogit1 <- glm(\n  valis ~ vanus + sugu + haridus + huvi_pol,\n  family = \"binomial\",\n  data = data\n)\n\nsummary(logit1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## \n## Call:\n## glm(formula = valis ~ vanus + sugu + haridus + huvi_pol, family = \"binomial\", \n##     data = data)\n## \n## Coefficients:\n##              Estimate Std. Error z value Pr(>|z|)    \n## (Intercept) -1.731733   0.301076  -5.752 8.83e-09 ***\n## vanus        0.011713   0.004147   2.824  0.00474 ** \n## sugunaine   -0.109644   0.148560  -0.738  0.46049    \n## haridus      0.403180   0.049425   8.157 3.42e-16 ***\n## huvi_pol     0.898893   0.155360   5.786 7.21e-09 ***\n## ---\n## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n## \n## (Dispersion parameter for binomial family taken to be 1)\n## \n##     Null deviance: 1330.6  on 1163  degrees of freedom\n## Residual deviance: 1178.1  on 1159  degrees of freedom\n##   (129 observations deleted due to missingness)\n## AIC: 1188.1\n## \n## Number of Fisher Scoring iterations: 4\n```\n\n\n:::\n:::\n\n\n## Tulemuste tõlgendamine\n\nKoefitsiendid on logiti skaalal. Nagu öeldud, ei ole nende arvuline väärtus otseselt\nmõistetav — aga **märk on.**\n\nVanus, haridus ja poliitikahuvi on kõik positiivsed ja statistiliselt olulised: vanemad,\nharitumad ja poliitikast rohkem huvitatud inimesed käivad suurema tõenäosusega valimas.\n\n### Šansside suhe\n\nLogiti koefitsienti ei saa otse tõlgendada. Aga kui teha talle logaritmi vastandtehe funktsiooniga `exp()`, saame arvu, mida saab — **šansside suhte** (*odds ratio*).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkoefitsiendid <- coef(logit1)\nsansside_suhted <- exp(koefitsiendid)\n\nround(sansside_suhted, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## (Intercept)       vanus   sugunaine     haridus    huvi_pol \n##       0.177       1.012       0.896       1.497       2.457\n```\n\n\n:::\n:::\n\n\n**Kuidas šansside suhet lugeda?**\n\nKõige olulisem on üks vahe, mida aetakse pidevalt segamini.\n\n> **Logiti koefitsient ütleb, mitme VÕRRA logit muutub. Šansside suhe ütleb, mitu KORDA šansid muutuvad.**\n>\n> Esimene on liitmine, teine on korrutamine. Sellepärast on nende võrdluspunktid ka erinevad: koefitsiendi puhul on \"seost ei ole\" väärtus **null**, šansside suhte puhul **üks**.\n\nSeega:\n\n| Šansside suhe | Mida tähendab |\n|---|---|\n| **üle 1** | šansid kasvavad — seos on positiivne |\n| **täpselt 1** | seost ei ole |\n| **alla 1** | šansid kahanevad — seos on negatiivne |\n\n**Näide meie mudelist.** Poliitikahuvi šansside suhe on 2.46. Muutuja on binaarne: 1 tähendab poliitikast huvitatud, 0 mitte huvitatud.\n\nTõlgendus: **poliitikast huvitatud inimeste šansid valimas käia on 2.46 korda suuremad kui mittehuvitatutel**, kui vanus ja haridus on samad.\n\nVanuse šansside suhe on 1.012. See tundub olematu, aga pane tähele skaalat: ta käib **ühe eluaasta** kohta. Kümne aasta kohta tuleb ta astmesse tõsta, mitte kümnega korrutada — ja siis on ta juba 1.12.\n\n> **Kaks lõksu, mille otsa komistatakse pidevalt.**\n>\n> **Esiteks: šansid ei ole tõenäosus.** Kui šansid kahekordistuvad, siis tõenäosus **ei** kahekordistu. Kui tõenäosus oli 0,5, siis šansid olid üks ühele; kahekordistudes saavad nad kaks ühele, mis vastab tõenäosusele 0,67 — mitte 1,0. Ja mida lähemal on tõenäosus ühele, seda vähem ta üldse muutub.\n>\n> **Teiseks: \"kaks korda suuremad šansid\" ei tähenda \"kaks korda tõenäolisem\".** Ajakirjanduses aetakse neid pidevalt segamini ja teadustöös ei tohi seda teha.\n\nJust sellepärast on ennustatud tõenäosuste joonis nii kasulik — seal on tavaline tõenäosus, mille tõlgendamisel eksida ei saa.\n\n::: {.harjutus}\n**Harjutus.** Arvuta hariduse šansside suhe kolme haridusastme kohta korraga (ehk tõsta ta kolmandasse astmesse). Kui palju kasvavad valimas käimise šansid, kui haridustase on kolm astet kõrgem?\n:::\n\n### Ennustatud tõenäosused\n\nKõige arusaadavam viis on ikkagi joonis. Sama funktsioon, mida praktikumis 10 kasutasime, töötab ka siin — ja ta teeb tagasiteisenduse tõenäosusteks ise ära, nii et y-teljel on tavaline tõenäosus, mitte logit.\n\nJoonisel kasutame ka funktsiooni `ylim()`, mis fikseerib y-telje ulatuse. Paneme ta 0-st 1-ni, sest tõenäosus saabki ainult selles vahemikus olla — nii on kohe näha, kui suur osa võimalikust skaalast tegelikult kasutuses on.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nennustus_huvi <- predict_response(logit1, terms = \"huvi_pol\")\nhuvi_tabel <- as.data.frame(ennustus_huvi)\nhuvi_tabel$x <- factor(huvi_tabel$x)\n\nggplot(huvi_tabel, aes(x = x, y = predicted)) +\n  geom_errorbar(\n    aes(ymin = conf.low, ymax = conf.high),\n    width = 0.15,\n    color = \"grey40\"\n  ) +\n  geom_point(size = 3, color = \"dodgerblue3\") +\n  scale_x_discrete(labels = c(\"ei ole huvitatud\", \"on huvitatud\")) +\n  ylim(0, 1) +\n  labs(\n    x = NULL,\n    y = \"tõenäosus valimas käia\",\n    title = \"Valimas käimise ennustatud tõenäosus\"\n  ) +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](11-logistiline-regressioon_files/figure-html/pred-joonis-1.png){width=672}\n:::\n:::\n\n\nSiit on kohe näha, mida mudel ütleb: kõige väiksema poliitikahuviga inimeste seas käib\nvalimas umbes 55%, kõige suurema huviga inimeste seas üle 90%.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nennustus_vanus <- predict_response(logit1, terms = \"vanus\")\nvanus_tabel <- as.data.frame(ennustus_vanus)\n\nggplot(vanus_tabel, aes(x = x, y = predicted)) +\n  geom_ribbon(aes(ymin = conf.low, ymax = conf.high), fill = \"grey80\") +\n  geom_line(linewidth = 1, color = \"dodgerblue3\") +\n  ylim(0, 1) +\n  labs(\n    x = \"vanus\",\n    y = \"tõenäosus valimas käia\",\n    title = \"Valimas käimise ennustatud tõenäosus\"\n  ) +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](11-logistiline-regressioon_files/figure-html/pred-vanus-1.png){width=672}\n:::\n:::\n\n\nPane tähele, et joon **ei ole sirge** — ta on otstest lamedam. Just see oligi logiti\nmõte.\n\n## Mudeli sobivus\n\nLogistilise regressiooni puhul ei saa arvutada tavalist R-ruutu. Selle asemel on\n**pseudo R-ruut** — arv, mis on tõlgendatav sarnaselt, kuid mitte päris samamoodi.\n\nNeid on mitu varianti ja nad on nimetatud oma väljamõtlejate järgi. Arvutab neid\nfunktsioon `pR2()` paketist `pscl`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# pR2() trükib arvutamise ajal teate null-mudeli sobitamise kohta.\n# suppressMessages() vaigistab selle -- tulemus ise ei muutu.\nsuppressMessages(pR2(logit1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## fitting null model for pseudo-r2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n##          llh      llhNull           G2     McFadden         r2ML         r2CU \n## -589.0625075 -665.3168512  152.5086874    0.1146136    0.1228008    0.1802743\n```\n\n\n:::\n:::\n\n\nKolm viimast arvu on pseudo R-ruudud: **McFadden** oma nime all, **Cox ja Snell** nime\nall `r2ML` ning **Nagelkerke** nime all `r2CU`.\n\n> Millist kasutada? Lõplikku konsensust ei ole. **McFadden** on kõige tavalisem ja jääb\n> oma hinnangult tavaliselt keskele — piirdu temaga.\n>\n> NB! McFadden pseudo R-ruut on tavaliselt **palju väiksem** kui tavaline R-ruut oleks, kui tema arvutamine antud juhul võimalik oleks. See on selle tõlgendamine samaväärselt tavalise R-ruuduga natuke komplitseeritud. Väärtus\n> 0,1 on logistilise mudeli puhul juba päris hea. Ära ehmata.\n\n### Klassifitseerimistäpsus\n\nTeine viis mudelit hinnata on küsida: **kui hästi ta juhtumeid ära arvab?**\n\nEnnustatud tõenäosused saab funktsiooniga `fitted()`. Kui neid ümardada, saame\nennustuse 0 või 1 — ümardamise piir on 0,5.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntoenaosused <- fitted(logit1)\nennustatud <- round(toenaosused)\n\n# Mudel jättis puuduvate väärtustega read välja, seega peame võtma\n# tegelikud väärtused mudeli enda andmetest, mitte algsest tabelist.\ntegelik <- logit1$model$valis\n\ntabel <- table(ennustatud, tegelik)\ntabel\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n##           tegelik\n## ennustatud   0   1\n##          0  62  28\n##          1 239 835\n```\n\n\n:::\n:::\n\n\n> **Miks me võtame tegelikud väärtused mudeli seest?** Sest `glm()` viskas puuduvate\n> väärtustega read välja ja `fitted()` annab tulemused ainult alles jäänud ridade kohta.\n> Kui võtta `data$valis`, oleksid vektorid eri pikkusega ja tabel tuleks vale.\n>\n> Juhtumite arvu mudelis annab `nobs()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnobs(logit1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## [1] 1164\n```\n\n\n:::\n:::\n\n\nSellest tabelist saab kaks olulist arvu.\n\n* **Sensitiivsus** — kui suure osa tegelikest valijatest mudel õigesti ära tundis.\n* **Spetsiifilisus** — kui suure osa tegelikest mittevalijatest mudel õigesti ära\n  tundis.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsensitiivsus <- tabel[2, 2] / sum(tabel[, 2])\nspetsiifilisus <- tabel[1, 1] / sum(tabel[, 1])\n\nround(c(sensitiivsus = sensitiivsus, spetsiifilisus = spetsiifilisus), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n##   sensitiivsus spetsiifilisus \n##          0.968          0.206\n```\n\n\n:::\n:::\n\n\nSensitiivsus on väga kõrge, spetsiifilisus madal. Mudel tunneb valijad hästi ära, aga\nmittevalijaid peaaegu üldse mitte.\n\nMiks? Sest valijaid on meie andmetes palju rohkem (871 vastu 304). Mudelil on\n\"turvaline\" ennustada kõigi kohta, et nad käivad valimas.\n\n> **Mõtle sellele koroonatesti näitel.** Sensitiivsus on testi võime leida üles haiged\n> inimesed. Spetsiifilisus on tema võime mitte anda valepositiivseid. Test, mis ütleb\n> kõigi kohta \"haige\", on 100% sensitiivne ja 0% spetsiifiline — ja täiesti kasutu.\n>\n> **Seetõttu tuleb neid alati koos vaadata.** Üksik arv ei ütle midagi.\n\nProovime paremat mudelit — lisame juurde muutujad, mis võiksid valimas käimist samuti seletada.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlogit2 <- glm(\n  valis ~ vanus + sugu + haridus + huvi_pol + usaldus_pol +\n    rahulolu_dem + sissetulek,\n  family = \"binomial\",\n  data = data\n)\n\nsummary(logit2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## \n## Call:\n## glm(formula = valis ~ vanus + sugu + haridus + huvi_pol + usaldus_pol + \n##     rahulolu_dem + sissetulek, family = \"binomial\", data = data)\n## \n## Coefficients:\n##               Estimate Std. Error z value Pr(>|z|)    \n## (Intercept)  -3.146103   0.444683  -7.075 1.50e-12 ***\n## vanus         0.021781   0.005199   4.190 2.79e-05 ***\n## sugunaine    -0.081661   0.166845  -0.489 0.624527    \n## haridus       0.284017   0.057734   4.919 8.68e-07 ***\n## huvi_pol      0.660853   0.173281   3.814 0.000137 ***\n## usaldus_pol   0.077645   0.043407   1.789 0.073653 .  \n## rahulolu_dem  0.114065   0.037725   3.024 0.002498 ** \n## sissetulek    0.140361   0.035734   3.928 8.57e-05 ***\n## ---\n## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n## \n## (Dispersion parameter for binomial family taken to be 1)\n## \n##     Null deviance: 1128.13  on 1034  degrees of freedom\n## Residual deviance:  963.92  on 1027  degrees of freedom\n##   (258 observations deleted due to missingness)\n## AIC: 979.92\n## \n## Number of Fisher Scoring iterations: 5\n```\n\n\n:::\n:::\n\n\nKas ta on parem? Vaatame kõiki kolme sobivusnäitajat korraga.\n\nSelle asemel et sama koodi kaks korda kirjutada, teeme **oma funktsiooni**. Funktsiooni loomine käib nii: nimi, `<-`, sõna `function`, sulgudes sisendite nimed ja looksulgudes see, mida teha. Viimane rida funktsiooni sees on see, mille ta tagastab.\n\nNimetame ta `sobivus()` — ta võtab sisendiks mudeli ja annab tagasi kolm sobivusnäitajat.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsobivus <- function(mudel) {\n  toenaosused <- fitted(mudel)\n  ennustatud <- round(toenaosused)\n  tegelik <- mudel$model[[1]]\n  tabel <- table(ennustatud, tegelik)\n\n  sens <- tabel[\"1\", \"1\"] / sum(tabel[, \"1\"])\n  spets <- tabel[\"0\", \"0\"] / sum(tabel[, \"0\"])\n  # pR2() trükib teate null-mudeli sobitamise kohta; suppressMessages() vaigistab ta\n  mcf <- suppressMessages(pR2(mudel))[[\"McFadden\"]]\n\n  tulemus <- c(\n    McFadden = mcf,\n    sensitiivsus = sens,\n    spetsiifilisus = spets,\n    n = nobs(mudel)\n  )\n\n  round(tulemus, 3)\n}\n```\n:::\n\n\nJa rakendame teda mõlemale mudelile.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsobivus(logit1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## fitting null model for pseudo-r2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n##       McFadden   sensitiivsus spetsiifilisus              n \n##          0.115          0.968          0.206       1164.000\n```\n\n\n:::\n\n```{.r .cell-code}\nsobivus(logit2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## fitting null model for pseudo-r2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n##       McFadden   sensitiivsus spetsiifilisus              n \n##          0.146          0.961          0.267       1035.000\n```\n\n\n:::\n:::\n\n\n\n\nPseudo R-ruut kasvas 0.115-lt 0.146-le ja spetsiifilisus\n0.206-lt 0.267-le. Mudel tunneb mittevalijaid\nparemini ära kui enne, kuigi endiselt halvasti.\n\n::: {.arutelu}\n**Arutelu.** Juhtumite arv langes 1164-lt 1035-le. **Miks?** Ja mida see\ntähendab nende kahe mudeli võrdlemise seisukohalt?\n:::\n\n## Tulemuste esitamine\n\nLogistilise regressiooni tabel peab sisaldama rohkem kui tavaline regressioonitabel:\nlisaks koefitsientidele ka **šansside suhted** ja mudeli sobivuse näitajad.\n\nPseudo R-ruutu, sensitiivsust ja spetsiifilisust `modelsummary()` ise ei tunne. Aga talle\nsaab õpetada: kui defineerida funktsioon nimega `glance_custom.glm`, siis kutsub\n`modelsummary()` teda iga logistilise mudeli kohta ja lisab tulemused tabeli alaossa.\n\nFunktsioon `sprintf()` vormindab arvu tekstiks. Kirjapilt `\"%.3f\"` tähendab \"arv kolme\nkomakohaga\". Seda on vaja, et tabelis oleks igal pool ühepalju komakohti.\n\nFunktsioon `registerS3method()` ütleb R-ile, et see uus funktsioon tuleb kasutusele võtta\nalati, kui `modelsummary()` kohtab logistilist mudelit.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglance_custom.glm <- function(x, ...) {\n  n <- sobivus(x)\n\n  data.frame(\n    McFadden = sprintf(\"%.3f\", n[[\"McFadden\"]]),\n    Sensitiivsus = sprintf(\"%.3f\", n[[\"sensitiivsus\"]]),\n    Spetsiifilisus = sprintf(\"%.3f\", n[[\"spetsiifilisus\"]])\n  )\n}\n\nregisterS3method(\"glance_custom\", \"glm\", glance_custom.glm)\n```\n:::\n\n\nNüüd teeme tabeli. Kaks mudelit kõrvuti, koefitsiendid logiti skaalal.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnimed <- c(\n  \"vanus\" = \"Vanus (aastates)\",\n  \"sugunaine\" = \"Sugu: naine (ref. mees)\",\n  \"haridus\" = \"Haridustase (1-7)\",\n  \"huvi_pol\" = \"Huvitatud poliitikast (ref. ei ole)\",\n  \"usaldus_pol\" = \"Usaldus poliitikute vastu (0-10)\",\n  \"rahulolu_dem\" = \"Rahulolu demokraatiaga (0-10)\",\n  \"sissetulek\" = \"Sissetulekudetsiil (1-10)\",\n  \"(Intercept)\" = \"Vabaliige\"\n)\n\nmodelsummary(\n  list(\"Mudel 1\" = logit1, \"Mudel 2\" = logit2),\n  coef_map = nimed,\n  gof_map = c(\"nobs\", \"McFadden\", \"Sensitiivsus\", \"Spetsiifilisus\"),\n  stars = c(\"*\" = 0.05, \"**\" = 0.01, \"***\" = 0.001),\n  title = \"Valimas käimist ennustavad tegurid (logiti koefitsiendid)\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## fitting null model for pseudo-r2\n## fitting null model for pseudo-r2\n```\n\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_bzfookve3bxfe5qnuggj = TinyTable.createTableFunctions(\"tinytable_bzfookve3bxfe5qnuggj\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '20', j: 2 }, { i: '20', j: 3 } ], css_id: 'tinytable_css_rbklwm0l2vb7fve7vbnb',}, \n          { positions: [ { i: '16', j: 2 }, { i: '16', j: 3 } ], css_id: 'tinytable_css_46ai2iqqbxw47vif4h07',}, \n          { positions: [ { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '4', j: 2 }, { i: '5', j: 2 }, { i: '6', j: 2 }, { i: '7', j: 2 }, { i: '8', j: 2 }, { i: '9', j: 2 }, { i: '10', j: 2 }, { i: '11', j: 2 }, { i: '12', j: 2 }, { i: '13', j: 2 }, { i: '14', j: 2 }, { i: '15', j: 2 }, { i: '17', j: 2 }, { i: '18', j: 2 }, { i: '19', j: 2 }, { i: '1', j: 3 }, { i: '2', j: 3 }, { i: '3', j: 3 }, { i: '4', j: 3 }, { i: '5', j: 3 }, { i: '6', j: 3 }, { i: '7', j: 3 }, { i: '8', j: 3 }, { i: '9', j: 3 }, { i: '10', j: 3 }, { i: '11', j: 3 }, { i: '12', j: 3 }, { i: '13', j: 3 }, { i: '14', j: 3 }, { i: '15', j: 3 }, { i: '17', j: 3 }, { i: '18', j: 3 }, { i: '19', j: 3 } ], css_id: 'tinytable_css_291xfevu073vxcto6ro0',}, \n          { positions: [ { i: '0', j: 2 }, { i: '0', j: 3 } ], css_id: 'tinytable_css_lvp7g2xrhphaxyhecwdw',}, \n          { positions: [ { i: '20', j: 1 } ], css_id: 'tinytable_css_15dbsqzp2kl00uk79k7c',}, \n          { positions: [ { i: '16', j: 1 } ], css_id: 'tinytable_css_xevw2pyfr7yqqld3p57j',}, \n          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '4', j: 1 }, { i: '5', j: 1 }, { i: '6', j: 1 }, { i: '7', j: 1 }, { i: '8', j: 1 }, { i: '9', j: 1 }, { i: '10', j: 1 }, { i: '11', j: 1 }, { i: '12', j: 1 }, { i: '13', j: 1 }, { i: '14', j: 1 }, { i: '15', j: 1 }, { i: '17', j: 1 }, { i: '18', j: 1 }, { i: '19', j: 1 } ], css_id: 'tinytable_css_7mvglokda3n0seymnf86',}, \n          { positions: [ { i: '0', j: 1 } ], css_id: 'tinytable_css_mla0fwknct32y71lfjzz',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_bzfookve3bxfe5qnuggj.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_bzfookve3bxfe5qnuggj td.tinytable_css_rbklwm0l2vb7fve7vbnb, #tinytable_bzfookve3bxfe5qnuggj th.tinytable_css_rbklwm0l2vb7fve7vbnb {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_bzfookve3bxfe5qnuggj td.tinytable_css_46ai2iqqbxw47vif4h07, #tinytable_bzfookve3bxfe5qnuggj th.tinytable_css_46ai2iqqbxw47vif4h07 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_bzfookve3bxfe5qnuggj td.tinytable_css_291xfevu073vxcto6ro0, #tinytable_bzfookve3bxfe5qnuggj th.tinytable_css_291xfevu073vxcto6ro0 { text-align: center }\n    #tinytable_bzfookve3bxfe5qnuggj td.tinytable_css_lvp7g2xrhphaxyhecwdw, #tinytable_bzfookve3bxfe5qnuggj th.tinytable_css_lvp7g2xrhphaxyhecwdw {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_bzfookve3bxfe5qnuggj td.tinytable_css_15dbsqzp2kl00uk79k7c, #tinytable_bzfookve3bxfe5qnuggj th.tinytable_css_15dbsqzp2kl00uk79k7c {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_bzfookve3bxfe5qnuggj td.tinytable_css_xevw2pyfr7yqqld3p57j, #tinytable_bzfookve3bxfe5qnuggj th.tinytable_css_xevw2pyfr7yqqld3p57j {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_bzfookve3bxfe5qnuggj td.tinytable_css_7mvglokda3n0seymnf86, #tinytable_bzfookve3bxfe5qnuggj th.tinytable_css_7mvglokda3n0seymnf86 { text-align: left }\n    #tinytable_bzfookve3bxfe5qnuggj td.tinytable_css_mla0fwknct32y71lfjzz, #tinytable_bzfookve3bxfe5qnuggj th.tinytable_css_mla0fwknct32y71lfjzz {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_bzfookve3bxfe5qnuggj\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        <caption>Valimas käimist ennustavad tegurid (logiti koefitsiendid)</caption>\n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\"> </th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">Mudel 1</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"3\">Mudel 2</th>\n              </tr>\n        </thead>\n        <tfoot><tr><td colspan='3'>* p < 0.05, ** p < 0.01, *** p < 0.001</td></tr></tfoot>\n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">Vanus (aastates)</td>\n                  <td data-row=\"1\" data-col=\"2\">0.012**</td>\n                  <td data-row=\"1\" data-col=\"3\">0.022***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\"></td>\n                  <td data-row=\"2\" data-col=\"2\">(0.004)</td>\n                  <td data-row=\"2\" data-col=\"3\">(0.005)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">Sugu: naine (ref. mees)</td>\n                  <td data-row=\"3\" data-col=\"2\">-0.110</td>\n                  <td data-row=\"3\" data-col=\"3\">-0.082</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"1\"></td>\n                  <td data-row=\"4\" data-col=\"2\">(0.149)</td>\n                  <td data-row=\"4\" data-col=\"3\">(0.167)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"1\">Haridustase (1-7)</td>\n                  <td data-row=\"5\" data-col=\"2\">0.403***</td>\n                  <td data-row=\"5\" data-col=\"3\">0.284***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"1\"></td>\n                  <td data-row=\"6\" data-col=\"2\">(0.049)</td>\n                  <td data-row=\"6\" data-col=\"3\">(0.058)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"7\" data-col=\"1\">Huvitatud poliitikast (ref. ei ole)</td>\n                  <td data-row=\"7\" data-col=\"2\">0.899***</td>\n                  <td data-row=\"7\" data-col=\"3\">0.661***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"8\" data-col=\"1\"></td>\n                  <td data-row=\"8\" data-col=\"2\">(0.155)</td>\n                  <td data-row=\"8\" data-col=\"3\">(0.173)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"9\" data-col=\"1\">Usaldus poliitikute vastu (0-10)</td>\n                  <td data-row=\"9\" data-col=\"2\"></td>\n                  <td data-row=\"9\" data-col=\"3\">0.078</td>\n                </tr>\n                <tr>\n                  <td data-row=\"10\" data-col=\"1\"></td>\n                  <td data-row=\"10\" data-col=\"2\"></td>\n                  <td data-row=\"10\" data-col=\"3\">(0.043)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"11\" data-col=\"1\">Rahulolu demokraatiaga (0-10)</td>\n                  <td data-row=\"11\" data-col=\"2\"></td>\n                  <td data-row=\"11\" data-col=\"3\">0.114**</td>\n                </tr>\n                <tr>\n                  <td data-row=\"12\" data-col=\"1\"></td>\n                  <td data-row=\"12\" data-col=\"2\"></td>\n                  <td data-row=\"12\" data-col=\"3\">(0.038)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"13\" data-col=\"1\">Sissetulekudetsiil (1-10)</td>\n                  <td data-row=\"13\" data-col=\"2\"></td>\n                  <td data-row=\"13\" data-col=\"3\">0.140***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"14\" data-col=\"1\"></td>\n                  <td data-row=\"14\" data-col=\"2\"></td>\n                  <td data-row=\"14\" data-col=\"3\">(0.036)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"15\" data-col=\"1\">Vabaliige</td>\n                  <td data-row=\"15\" data-col=\"2\">-1.732***</td>\n                  <td data-row=\"15\" data-col=\"3\">-3.146***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"16\" data-col=\"1\"></td>\n                  <td data-row=\"16\" data-col=\"2\">(0.301)</td>\n                  <td data-row=\"16\" data-col=\"3\">(0.445)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"17\" data-col=\"1\">Num.Obs.</td>\n                  <td data-row=\"17\" data-col=\"2\">1164</td>\n                  <td data-row=\"17\" data-col=\"3\">1035</td>\n                </tr>\n                <tr>\n                  <td data-row=\"18\" data-col=\"1\">McFadden</td>\n                  <td data-row=\"18\" data-col=\"2\">0.115</td>\n                  <td data-row=\"18\" data-col=\"3\">0.146</td>\n                </tr>\n                <tr>\n                  <td data-row=\"19\" data-col=\"1\">Sensitiivsus</td>\n                  <td data-row=\"19\" data-col=\"2\">0.968</td>\n                  <td data-row=\"19\" data-col=\"3\">0.961</td>\n                </tr>\n                <tr>\n                  <td data-row=\"20\" data-col=\"1\">Spetsiifilisus</td>\n                  <td data-row=\"20\" data-col=\"2\">0.206</td>\n                  <td data-row=\"20\" data-col=\"3\">0.267</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\nKõik sobivusnäitajad on nüüd tabelis olemas ja iga mudeli kohta eraldi.\n\n**Ja šansside suhted?** Nende jaoks teeme eraldi tabeli argumendiga\n`exponentiate = TRUE`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelsummary(\n  list(\"Mudel 1\" = logit1, \"Mudel 2\" = logit2),\n  exponentiate = TRUE,\n  coef_map = nimed[names(nimed) != \"(Intercept)\"],\n  gof_map = c(\"nobs\", \"McFadden\"),\n  stars = c(\"*\" = 0.05, \"**\" = 0.01, \"***\" = 0.001),\n  title = \"Valimas käimist ennustavad tegurid (šansside suhted)\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## fitting null model for pseudo-r2\n## fitting null model for pseudo-r2\n```\n\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_d8mslqhenvqdclo6s253 = TinyTable.createTableFunctions(\"tinytable_d8mslqhenvqdclo6s253\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '16', j: 2 }, { i: '16', j: 3 } ], css_id: 'tinytable_css_pp9leo4wmp7437f5hsxz',}, \n          { positions: [ { i: '14', j: 2 }, { i: '14', j: 3 } ], css_id: 'tinytable_css_4m8ke2m0oobkacjk6e7a',}, \n          { positions: [ { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '4', j: 2 }, { i: '5', j: 2 }, { i: '6', j: 2 }, { i: '7', j: 2 }, { i: '8', j: 2 }, { i: '9', j: 2 }, { i: '10', j: 2 }, { i: '11', j: 2 }, { i: '12', j: 2 }, { i: '13', j: 2 }, { i: '15', j: 2 }, { i: '1', j: 3 }, { i: '2', j: 3 }, { i: '3', j: 3 }, { i: '4', j: 3 }, { i: '5', j: 3 }, { i: '6', j: 3 }, { i: '7', j: 3 }, { i: '8', j: 3 }, { i: '9', j: 3 }, { i: '10', j: 3 }, { i: '11', j: 3 }, { i: '12', j: 3 }, { i: '13', j: 3 }, { i: '15', j: 3 } ], css_id: 'tinytable_css_hholm9wfagszt3p9078g',}, \n          { positions: [ { i: '0', j: 2 }, { i: '0', j: 3 } ], css_id: 'tinytable_css_6bwe0tyhw2zahj1fpjna',}, \n          { positions: [ { i: '16', j: 1 } ], css_id: 'tinytable_css_qtiyq2id725k7ooh5gcg',}, \n          { positions: [ { i: '14', j: 1 } ], css_id: 'tinytable_css_v3lrygsl6ilsib0oml4x',}, \n          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '4', j: 1 }, { i: '5', j: 1 }, { i: '6', j: 1 }, { i: '7', j: 1 }, { i: '8', j: 1 }, { i: '9', j: 1 }, { i: '10', j: 1 }, { i: '11', j: 1 }, { i: '12', j: 1 }, { i: '13', j: 1 }, { i: '15', j: 1 } ], css_id: 'tinytable_css_9ik9dphveckvi02wk7lg',}, \n          { positions: [ { i: '0', j: 1 } ], css_id: 'tinytable_css_y74vswpgv87wn3kadch1',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_d8mslqhenvqdclo6s253.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_d8mslqhenvqdclo6s253 td.tinytable_css_pp9leo4wmp7437f5hsxz, #tinytable_d8mslqhenvqdclo6s253 th.tinytable_css_pp9leo4wmp7437f5hsxz {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_d8mslqhenvqdclo6s253 td.tinytable_css_4m8ke2m0oobkacjk6e7a, #tinytable_d8mslqhenvqdclo6s253 th.tinytable_css_4m8ke2m0oobkacjk6e7a {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_d8mslqhenvqdclo6s253 td.tinytable_css_hholm9wfagszt3p9078g, #tinytable_d8mslqhenvqdclo6s253 th.tinytable_css_hholm9wfagszt3p9078g { text-align: center }\n    #tinytable_d8mslqhenvqdclo6s253 td.tinytable_css_6bwe0tyhw2zahj1fpjna, #tinytable_d8mslqhenvqdclo6s253 th.tinytable_css_6bwe0tyhw2zahj1fpjna {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_d8mslqhenvqdclo6s253 td.tinytable_css_qtiyq2id725k7ooh5gcg, #tinytable_d8mslqhenvqdclo6s253 th.tinytable_css_qtiyq2id725k7ooh5gcg {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_d8mslqhenvqdclo6s253 td.tinytable_css_v3lrygsl6ilsib0oml4x, #tinytable_d8mslqhenvqdclo6s253 th.tinytable_css_v3lrygsl6ilsib0oml4x {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_d8mslqhenvqdclo6s253 td.tinytable_css_9ik9dphveckvi02wk7lg, #tinytable_d8mslqhenvqdclo6s253 th.tinytable_css_9ik9dphveckvi02wk7lg { text-align: left }\n    #tinytable_d8mslqhenvqdclo6s253 td.tinytable_css_y74vswpgv87wn3kadch1, #tinytable_d8mslqhenvqdclo6s253 th.tinytable_css_y74vswpgv87wn3kadch1 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_d8mslqhenvqdclo6s253\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        <caption>Valimas käimist ennustavad tegurid (šansside suhted)</caption>\n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\"> </th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">Mudel 1</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"3\">Mudel 2</th>\n              </tr>\n        </thead>\n        <tfoot><tr><td colspan='3'>* p < 0.05, ** p < 0.01, *** p < 0.001</td></tr></tfoot>\n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">Vanus (aastates)</td>\n                  <td data-row=\"1\" data-col=\"2\">1.012**</td>\n                  <td data-row=\"1\" data-col=\"3\">1.022***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\"></td>\n                  <td data-row=\"2\" data-col=\"2\">(0.004)</td>\n                  <td data-row=\"2\" data-col=\"3\">(0.005)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">Sugu: naine (ref. mees)</td>\n                  <td data-row=\"3\" data-col=\"2\">0.896</td>\n                  <td data-row=\"3\" data-col=\"3\">0.922</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"1\"></td>\n                  <td data-row=\"4\" data-col=\"2\">(0.133)</td>\n                  <td data-row=\"4\" data-col=\"3\">(0.154)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"1\">Haridustase (1-7)</td>\n                  <td data-row=\"5\" data-col=\"2\">1.497***</td>\n                  <td data-row=\"5\" data-col=\"3\">1.328***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"1\"></td>\n                  <td data-row=\"6\" data-col=\"2\">(0.074)</td>\n                  <td data-row=\"6\" data-col=\"3\">(0.077)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"7\" data-col=\"1\">Huvitatud poliitikast (ref. ei ole)</td>\n                  <td data-row=\"7\" data-col=\"2\">2.457***</td>\n                  <td data-row=\"7\" data-col=\"3\">1.936***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"8\" data-col=\"1\"></td>\n                  <td data-row=\"8\" data-col=\"2\">(0.382)</td>\n                  <td data-row=\"8\" data-col=\"3\">(0.336)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"9\" data-col=\"1\">Usaldus poliitikute vastu (0-10)</td>\n                  <td data-row=\"9\" data-col=\"2\"></td>\n                  <td data-row=\"9\" data-col=\"3\">1.081</td>\n                </tr>\n                <tr>\n                  <td data-row=\"10\" data-col=\"1\"></td>\n                  <td data-row=\"10\" data-col=\"2\"></td>\n                  <td data-row=\"10\" data-col=\"3\">(0.047)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"11\" data-col=\"1\">Rahulolu demokraatiaga (0-10)</td>\n                  <td data-row=\"11\" data-col=\"2\"></td>\n                  <td data-row=\"11\" data-col=\"3\">1.121**</td>\n                </tr>\n                <tr>\n                  <td data-row=\"12\" data-col=\"1\"></td>\n                  <td data-row=\"12\" data-col=\"2\"></td>\n                  <td data-row=\"12\" data-col=\"3\">(0.042)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"13\" data-col=\"1\">Sissetulekudetsiil (1-10)</td>\n                  <td data-row=\"13\" data-col=\"2\"></td>\n                  <td data-row=\"13\" data-col=\"3\">1.151***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"14\" data-col=\"1\"></td>\n                  <td data-row=\"14\" data-col=\"2\"></td>\n                  <td data-row=\"14\" data-col=\"3\">(0.041)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"15\" data-col=\"1\">Num.Obs.</td>\n                  <td data-row=\"15\" data-col=\"2\">1164</td>\n                  <td data-row=\"15\" data-col=\"3\">1035</td>\n                </tr>\n                <tr>\n                  <td data-row=\"16\" data-col=\"1\">McFadden</td>\n                  <td data-row=\"16\" data-col=\"2\">0.115</td>\n                  <td data-row=\"16\" data-col=\"3\">0.146</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\n> **Miks kaks eraldi tabelit, mitte kaks veergu ühes?** Kui panna sama mudel tabelisse\n> kaks korda — üks kord koefitsientidena ja teine kord šansside suhetena — siis korratakse\n> ka kõiki sobivusnäitajaid. Need on mõlemal veerul täpselt samad, sest tegemist on ühe\n> ja sama mudeliga. Tabelisse tekib mõttetut kordust.\n>\n> Vabaliige on šansside suhete tabelist välja jäetud, sest tema eksponent ei ole\n> sisuliselt tõlgendatav.\n\nJa tabeli saab Wordi täpselt nii, nagu eelmises praktikumis.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelsummary(\n  list(\"Koefitsiendid (logit)\" = logit1, \"Šansside suhted\" = logit1),\n  exponentiate = c(FALSE, TRUE),\n  coef_map = nimed,\n  gof_map = c(\"nobs\", \"aic\"),\n  stars = c(\"*\" = 0.05, \"**\" = 0.01, \"***\" = 0.001),\n  output = \"logit_tabel.docx\"\n)\n```\n:::\n\n\n## Kuidas seda kirja panna\n\n::: {.callout-tip title=\"Kuidas seda kirja panna\"}\nLogistilise regressiooni esitamisel tuleb arvestada kolme asja, mida tavalise regressiooni puhul ei\nolnud: **šansside suhted**, **pseudo R-ruut** ja **klassifitseerimistäpsus**.\n\n**Valimas käimise ennustamiseks koostati logistiline regressioonimudel (tabel 2), kuhu\nkaasati 1170 vastajat. Kõige tugevam seos ilmnes poliitikahuviga: iga punkti võrra\nsuurem huvi poliitika vastu suurendab valimas käimise šansse 2,1 korda (p < 0,001).\nStatistiliselt oluline oli ka vanus — iga eluaasta suurendab šansse 1,03 korda\n(p < 0,001) — ning haridustase (šansside suhe 1,14; p < 0,01). Soo puhul olulist seost\nei ilmnenud.**\n\n**Mudeli seletusvõime on tagasihoidlik (McFadden pseudo R² = 0,09). Mudel klassifitseerib\nvalijad hästi (sensitiivsus 98%), kuid mittevalijaid praktiliselt ei tuvasta\n(spetsiifilisus 8%).**\n\nNeli asja, mille peale mõelda:\n\n* **Ütle, mis on sõltuva muutuja puhul kodeeritud kui 1.** Ilma selleta ei tea lugeja, kumba suunda\n  koefitsient näitab.\n* **Šansside suhe on \"korda\", mitte \"võrra\".** Šansside suhe 2,1 tähendab\n  kahekordistumist, mitte 2,1 protsendipunkti.\n* **Ära aja segamini šansse ja tõenäosust.** Šansside kahekordistumine ei tähenda\n  tõenäosuse kahekordistumist.\n* **Raporteeri sensitiivsus ja spetsiifilisus koos.** Üksik arv on eksitav.\n:::\n\n## Kursuse lõpp\n\nSellega on käesolev kursus läbi.\n\nSa oskad nüüd võtta päris andmestiku, teha temast analüüsivalmis andmestiku, kirjeldada\noma muutujaid, hinnata ebakindlust, testida hüpoteese ning koostada ja esitada\nregressioonimudeleid nii pideva kui binaarse sõltuva muutuja jaoks.\n\nSee on väga suur hulk teadmisi, sa võib auga enda üle uhke olla!\n\n> Sellest piisab, et teha oma bakalaureusetöö jaoks kohane statistiline analüüs. Kuid\n> laiemas pildis on see alles algus — statistilise analüüsi maailm on peaaegu piiritu ja\n> pidevalt arenev. Selle valdkonna baasteadmised jäävad aga alati samaks ning nende\n> põhjal on alati võimalik edasi liikuda.\n\n## Harjutused\n\n::: {.harjutus}\n**1. Oma mudel.** Sobita logistiline mudel, kus sõltuv muutuja on `valis` ja sõltumatud on sinu enda valitud kolm muutujat. Põhjenda valikut.\n\n**2. Šansside suhted.** Arvuta oma mudeli šansside suhted ja tõlgenda neist kaks sõnadega.\n\n**3. Joonis.** Tee ennustatud tõenäosuste joonis ühe sõltumatu muutuja kohta. Kui palju tõenäosus skaala ühest otsast teise muutub?\n\n**4. Mudeli sobivus.** Arvuta oma mudeli pseudo R-ruut, sensitiivsus ja spetsiifilisus. Kumb neist kahest on kõrgem ja miks?\n\n**5. Kokkuvõte.** Kirjuta oma mudeli tulemused välja nii, nagu nad võiksid olla bakalaureusetöös.\n:::\n",
    "supporting": [
      "11-logistiline-regressioon_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}