{
  "hash": "f5403e6413cc7b01de9666b0649fb4d4",
  "result": {
    "engine": "knitr",
    "markdown": "# 2. Andmete laadimine\n\nEelmises praktikumis tegime ise väikese andmetabeli. Päris töös nii ei lähe — andmed\ntulevad kuskilt mujalt ja meie esimene ülesanne on nad R-i sisse saada.\n\n## Kust meie andmed tulevad?\n\nKogu kursuse vältel kasutame **Euroopa Sotsiaaluuringu** (*European Social Survey*, ESS)\nandmeid.\n\nESS on suur rahvusvaheline küsitlusuuring, mida on läbi viidud alates 2001. aastast\numbes iga kahe aasta tagant. Ta mõõdab inimeste hoiakuid, väärtusi ja käitumist\nkolmekümnes Euroopa riigis. Uuringut rahastatakse avalikest vahenditest ja **andmed on\nkõigile tasuta kättesaadavad** — seetõttu on ESS üks kõige laialdasemalt kasutatavaid\nandmestikke Euroopa sotsiaalteadustes.\n\nMeie kasutame **11. vooru** (ESS11), mille andmed koguti aastatel 2023–2024, ja sealt\n**Eesti osa**: 1293 vastajat.\n\nMõned asjad, mida ESS-i kohta teada tasub:\n\n* **Valim on juhuvalim.** Vastajad ei ole vabatahtlikud, kes ise kuskil registreerusid.\n  Nad on juhuslikult välja valitud kogu Eesti elanikkonnast. See on kõige olulisem\n  asjaolu, mis lubab meil hiljem oma valimi põhjal üldistusi teha.\n* **Küsitlus on näost näkku.** Intervjueerija käib kodus ja küsib küsimused ette.\n* **Küsimustik on kahes osas.** Üks osa on igas voorus sama (usaldus, poliitiline huvi,\n  hoiakud sisserände suhtes), teine osa vahetub — igas voorus on üks või kaks\n  eriteemat. ESS11 eriteema oli tervis ja heaolu.\n\n> **Viitamine.** Kui sa kasutad ESS-i andmeid oma töös, siis pead neile viitama. Meie\n> andmestiku viide on:\n>\n> European Social Survey European Research Infrastructure (ESS ERIC) (2026). *ESS11 —\n> integrated file, edition 4.2.* Sikt — Norwegian Agency for Shared Services in Education\n> and Research. doi:10.21338/ess11e04_2\n\nKui sa tahad hiljem oma bakalaureusetöö jaoks ESS-i andmeid, siis saad nad ise alla\nlaadida aadressilt [europeansocialsurvey.org](https://www.europeansocialsurvey.org).\nSelleks tuleb luua tasuta konto.\n\n## Koodiraamat\n\nAndmefail üksi ei ütle sulle midagi. Muutuja nimi andmestiks on `lrscale` ja väärtus on 7 — mida\nsee tähendab?\n\nSelle jaoks on **koodiraamat** (*codebook*). See on dokument, kus on kirjas iga muutuja\nkohta:\n\n* mis on tema nimi failis;\n* mis küsimus vastajale täpselt esitati, sõna-sõnalt;\n* mis väärtused on võimalikud ja mida iga väärtus tähendab;\n* kuidas on tähistatud puuduvad väärtused.\n\nESS-i koodiraamat on meil failis `ESS11 codebook.html`. Ava ta oma veebilehitsejas ja\notsi sealt üles muutuja `lrscale`.\n\n> **Ilma koodiraamatuta ei saa andmetega tööd teha.** Mitte \"on raskem\" — ei saa. Sa ei\n> tea, mida arvud tähendavad, sa ei tea, kummas skaala otsas on \"rohkem\", ja sa ei tea, millised\n> koodid tähendavad tegelikult \"ei oska öelda\".\n>\n> Enne kui sa mõnda muutujat kasutad, vaata ta koodiraamatust üle. Iga kord. See on\n> viieminutiline töö, mis päästab sind tundide kaupa segadusest.\n\nKõige olulisem küsimus, mida koodiraamatult küsida: **kummas otsas on rohkem?**\nKüsitlustes on väga tavaline, et skaala on \"tagurpidi\" — näiteks 1 = väga huvitatud ja\n4 = üldse mitte huvitatud. Ehk siis suurem number tähistab tegelikult vähemal määral seda omadust, mida see muutuja mõõdab. Kui sa seda ei märka, siis tuleb kogu su analüüs\nvastupidises suunas ja järeldused rist vastupidised võrreldes sellega, mis on õige. \n\n## Failiformaadid\n\nAndmed võivad tulla mitmes formaadis. Igaühe R-i laadimise jaoks on oma funktsioon.\n\n### R-i enda formaat\n\nR-il on oma andmeformaat laiendiga `.rdata` (või `.RData`). Seda on kõige lihtsam\nsalvestada ja laadida.\n\n* `load()` loeb faili töökeskkonda. Ainus argument on faili nimi.\n* `save()` salvestab. Esimene argument on objekt, mida salvestada, ja argument `file`\n  ütleb, mis nimega fail teha.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nload(\"data/ess11_ee_clean.rdata\")\nsave(data, file = \"data/minu_andmed.rdata\")\n```\n:::\n\n\nPane tähele üht erisust: `load()` **ei vaja** objekti nime. Fail teab ise, mis objektid\ntema sees on, ja nad ilmuvad töökeskkonda oma nimedega. Seetõttu tasub `load()` järel\nalati vaadata, mis töökeskkonda tekkis.\n\n> Kui sa töötad R-ga, siis on mõistlik oma töödeldud andmed salvestada just selles\n> formaadis. Ta on mahult väike, kiire ja säilitab kõik — faktorid, sildid, andmetüübid.\n\n### CSV failid\n\nCSV (*comma separated values*) on kõige ühilduvam formaat. Sisuliselt on tegemist\ntekstifailiga, kus väärtused on eraldatud komadega. Lugemiseks on funktsioon `read.csv()` ja salvestamiseks `write.csv()`.\n\nKolm argumenti, mida läheb peaaegu alati vaja:\n\n* `sep` ütleb, **mis märk väärtusi üksteisest eraldab**. Vaikimisi on see koma, aga see ei ole sugugi alati nii — Euroopas kasutatakse sageli semikoolonit, sest koma on siin kümnendkohaeraldaja. Kui fail avaneb ühe pika segase veeruna, siis on peaaegu alati just see argument valesti.\n* `header` ütleb, kas **esimeses reas on muutujate nimed** või juba andmed.\n* `row.names` ütleb salvestamisel, kas ridade numbrid tuleb eraldi veeruna faili kirjutada. Enamasti ei ole vaja.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nandmed <- read.csv(\"fail.csv\", sep = \",\", header = TRUE)\nwrite.csv(andmed, file = \"valjund.csv\", row.names = FALSE)\n```\n:::\n\n\n> CSV on hea vahetusformaat, aga tal on üks suur puudus: ta **ei säilita mitte\n> midagi** peale toorete väärtuste. Sildid, faktorid, puuduvate väärtuste\n> definitsioonid — kõik kaob.\n\n### SPSS failid\n\nSPSS on statistikaprogramm, mida on küsitlusuuringutes kaua kasutatud, ja väga paljud\nandmestikud — sealhulgas ESS — on saadaval ka selles formaadis, laiendiga `.sav`.\n\nSelle lugemiseks kasutame paketti **haven** ja funktsiooni `read_sav()`. Tulemuse\nmõõtmeid — esmalt ridade, siis veergude arvu — näitab funktsioon `dim()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(haven)\n\nee <- read_sav(\"data/ess11_ee_raw.sav\")\n\ndim(ee)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## [1] 1293  426\n```\n\n\n:::\n:::\n\n\nMeil on 1293 vastajat ja 426 muutujat.\n\n> **Vanemates materjalides õpetatakse funktsiooni `read.spss()` paketist `foreign`.**\n> See töötab ka, aga on aeglane ja kaotab osa infost. `haven::read_sav()` on tänapäeval\n> standard. Kui sa kohtad kuskil vana koodi, siis tea, mis see on — aga ise kasuta uut.\n\n### Stata failid\n\nStata on veel üks statistikaprogramm, laiend `.dta`. Sama pakett `haven` loeb ka neid —\nselleks on funktsioon `read_dta()`, mis töötab täpselt nagu `read_sav()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nandmed <- read_dta(\"fail.dta\")\n```\n:::\n\n\n## Esmane pilk andmetele\n\nKui andmed on sees, siis mida esimesena teha?\n\nFunktsioon `head()` näitab esimesi ridu.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(ee[, c(\"idno\", \"agea\", \"gndr\", \"lrscale\")])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## # A tibble: 6 × 4\n##    idno agea      gndr       lrscale  \n##   <dbl> <dbl+lbl> <dbl+lbl>  <dbl+lbl>\n## 1 50030 36        1 [Male]    5 [5]   \n## 2 50069 82        2 [Female]  5 [5]   \n## 3 50119 69        1 [Male]    8 [8]   \n## 4 50137 69        2 [Female] NA       \n## 5 50147 69        2 [Female] NA       \n## 6 50160 51        1 [Male]    5 [5]\n```\n\n\n:::\n:::\n\n\nFunktsioon `str()` näitab objekti struktuuri — muutujad, nende tüübid ja esimesed\nväärtused.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(ee[, c(\"idno\", \"agea\", \"gndr\", \"lrscale\")])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## tibble [1,293 × 4] (S3: tbl_df/tbl/data.frame)\n##  $ idno   : num [1:1293] 50030 50069 50119 50137 50147 ...\n##   ..- attr(*, \"label\")= chr \"Respondent's identification number\"\n##   ..- attr(*, \"format.spss\")= chr \"F8.2\"\n##  $ agea   : dbl+lbl [1:1293] 36, 82, 69, 69, 69, 51, 16, 41, 75, 17, 29, 46, 57, 6...\n##    ..@ label      : chr \"Age of respondent, calculated\"\n##    ..@ format.spss: chr \"F8.2\"\n##    ..@ labels     : Named num 999\n##    .. ..- attr(*, \"names\")= chr \"Not available\"\n##  $ gndr   : dbl+lbl [1:1293] 1, 2, 1, 2, 2, 1, 2, 2, 2, 2, 2, 1, 2, 2, 1, 2, 1, 2,...\n##    ..@ label      : chr \"Gender\"\n##    ..@ format.spss: chr \"F8.2\"\n##    ..@ labels     : Named num [1:3] 1 2 9\n##    .. ..- attr(*, \"names\")= chr [1:3] \"Male\" \"Female\" \"No answer\"\n##  $ lrscale: dbl+lbl [1:1293]  5,  5,  8, NA, NA,  5,  5,  5, NA,  5,  5,  2,  7,  ...\n##    ..@ label      : chr \"Placement on left right scale\"\n##    ..@ format.spss: chr \"F8.2\"\n##    ..@ labels     : Named num [1:14] 0 1 2 3 4 5 6 7 8 9 ...\n##    .. ..- attr(*, \"names\")= chr [1:14] \"Left\" \"1\" \"2\" \"3\" ...\n##  - attr(*, \"label\")= chr \"ESS11 edition 4.2, Eesti\"\n```\n\n\n:::\n:::\n\n\nFunktsioon `summary()` annab igast muutujast kokkuvõtte.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(ee[, c(\"agea\", \"lrscale\")])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n##       agea          lrscale      \n##  Min.   :15.00   Min.   : 0.000  \n##  1st Qu.:37.00   1st Qu.: 5.000  \n##  Median :50.00   Median : 5.000  \n##  Mean   :50.07   Mean   : 5.672  \n##  3rd Qu.:64.00   3rd Qu.: 7.000  \n##  Max.   :90.00   Max.   :10.000  \n##  NAs    :7       NAs    :185\n```\n\n\n:::\n:::\n\n\nFunktsioon `table()` teeb sagedustabeli — loendab, mitu korda iga väärtus esineb.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(ee$gndr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## \n##   1   2 \n## 577 716\n```\n\n\n:::\n:::\n\n\nJa RStudios saab andmetabelit vaadata ka tabelina: tee \"Environment\" aknas objekti nimel\nhiireklõps.\n\nKui objekti enam vaja ei lähe, saab ta töökeskkonnast eemaldada funktsiooniga `rm()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrm(ee)\n```\n:::\n\n\n## Muutujate skaalad\n\nEnne kui edasi läheme, kordame üle kõige olulisema asja, mida muutuja kohta teada tuleb:\n**mis skaalal ta on mõõdetud.** Sellest sõltub, millist analüüsi temaga üldse teha\ntohib.\n\nMuutujad jagunevad kõige üldisemalt kaheks: **pidevad** ja **kategoorilised**.\n\n### Pidevad muutujad\n\nPidevad muutujad on arvulised muutujad, mis võivad kahe arvu vahel võtta ükskõik\nmillise väärtuse. Tüüpiliselt on need nähtused, mis \"loomulikult\" esinevad numbritena —\nvanus, sissetulek eurodes, pikkus.\n\nPidevatel muutujatel on kaks alaliiki. Kõige lihtsam viis nende eristamiseks on küsida:\n**kas 0 tähendab selle nähtuse puudumist?**\n\n* Kui jah — **suhteskaala**. Näiteks raha või vanus: 0 eurot tähendab, et raha ei ole.\n* Kui ei — **intervallskaala**. Näiteks temperatuur Celsiuse skaalal: 0 kraadi ei\n  tähenda, et temperatuuri ei ole.\n\nNende meetodite puhul, mida me sellel kursusel vaatame, ei ole nende kahe vahel vahet.\nOluline on ainult teada, kas muutuja on pidev või mitte.\n\n### Kategoorilised muutujad\n\nKategoorilised muutujad jagavad juhtumid gruppidesse. Ka nemad jagunevad kaheks,\nsõltuvalt sellest, kas kategooriatel on **järjestus**.\n\n* **Ordinaalne** muutuja — kategooriatel on järjestus. Näiteks haridustase või\n  sissetulekudetsiil: on selge, milline kategooria on \"suurem\".\n* **Nominaalne** muutuja — järjestust ei ole. Näiteks erakondlik eelistus või elukoha\n  maakond. Ei ole mõtet küsida, kas Reformierakond on Keskerakonnast \"suurem\".\n\n**Binaarne** muutuja on kategoorilise muutuja erivorm, millel on täpselt kaks\nkategooriat — näiteks kas käis valimas või ei käinud. Neid kodeeritakse tavaliselt\narvudega 0 ja 1 ning nad on regressioonimudelites eriti kasulikud.\n\n### Praktiline reegel\n\nPiir ordinaalsete ja pidevate muutujate vahel on hägune. Küsitlusuuringutes on\npeaaegu kõik muutujad rangelt võttes ordinaalsed.\n\n> **Reegel, mida sellel kursusel kasutame:** kui ordinaalsel muutujal on **viis või\n> enam kategooriat**, mis on järjest nummerdatud, siis võib teda statistilises mõttes\n> käsitleda pideva muutujana. Sellisel juhul ei ole pidevate muutujatega seotud\n> statistilised eeldused liiga palju rikutud.\n\nMeie andmestikus tähendab see näiteks, et vasak-parem enesepaigutust (skaala 0–10) ja\nusaldust poliitikute vastu (0–10) võime käsitleda pidevatena, aga poliitilist huvi\n(neli kategooriat) mitte.\n\n## Järgmiseks\n\nNüüd, kus andmed on sees ja me teame, mida muutujate skaalad tähendavad, saame hakata\nandmestikku korda tegema. Sellega tegeleme kahes järgmises praktikumis — ja see on\nkursuse kõige praktilisem osa.\n\n## Harjutused\n\n::: {.harjutus}\n**1. Koodiraamat.** Otsi ESS-i koodiraamatust üles muutujad `stfeco`, `happy` ja `rlgatnd`. Kirjuta iga kohta välja: mis küsimus esitati, mis on skaala ulatus ja **kummas otsas on rohkem**.\n\n**2. Andmete sisse lugemine.** Loe fail `data/ess11_ee_raw.sav` sisse ja vaata, mitu rida ja veergu seal on. Vaata funktsiooniga `summary()` muutujat `agea` — mis on kõige noorem ja kõige vanem vastaja?\n\n**3. Skaalad.** Otsusta iga muutuja kohta, mis skaalal ta on mõõdetud ja kas teda võib käsitleda pidevana: `gndr`, `eisced`, `happy`, `prtvtiee`, `agea`. Põhjenda.\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}