{
  "hash": "6587ca5e76e8cb4d7fb5be0f6397dc6e",
  "result": {
    "engine": "knitr",
    "markdown": "# 8. Korrelatsioon\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\nlibrary(ggplot2)\nload(\"data/ess11_ee_clean.rdata\")\n```\n:::\n\n\nEelmises praktikumis võrdlesime kahe grupi keskmisi — seos ühe kategoorilise ja ühe pideva muutuja vahel. Nüüd astume sammu edasi ja vaatame **seost kahe pideva muutuja vahel.**\n\nSelleks on kaks tööriista, mis on omavahel tihedalt seotud:\n\n* **korrelatsioon** ütleb, **kui tugev** seos on ja **mis suunas** ta käib;\n* **regressioon** ütleb, **milline seos täpselt on** — kui palju üks muutuja muutub, kui teine muutub ühe ühiku võrra.\n\nSelles praktikumis tegeleme esimesega. Regressioon on järgmise praktikumi teema.\n\n## Hajuvusdiagramm\n\nAlusta alati pildist. Vaatame, kuidas on omavahel seotud usaldus poliitikute vastu ja\nrahulolu demokraatiaga.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data, aes(x = usaldus_pol, y = rahulolu_dem)) +\n  geom_point() +\n  labs(\n    x = \"usaldus poliitikute vastu (0-10)\",\n    y = \"rahulolu demokraatiaga (0-10)\",\n    title = \"Usaldus ja rahulolu\"\n  ) +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](08-korrelatsioon_files/figure-html/scatter-esimene-1.png){width=672}\n:::\n:::\n\n\nPunktid on ridades, sest mõlemad muutujad võtavad ainult täisarvulisi väärtusi. Väga\npalju vastajaid satub täpselt üksteise peale ja me ei näe, kui palju neid kuskil on.\n\nSelle vastu on kaks abinõu.\n\n* `geom_jitter()` nihutab iga punkti natuke juhuslikult paigast, nii et nad ei kata\n  üksteist. Argumendid `width` ja `height` määravad, kui palju.\n* Argument `alpha` teeb punktid läbipaistvaks.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data, aes(x = usaldus_pol, y = rahulolu_dem)) +\n  geom_jitter(width = 0.25, height = 0.25, alpha = 0.3) +\n  labs(\n    x = \"usaldus poliitikute vastu (0-10)\",\n    y = \"rahulolu demokraatiaga (0-10)\",\n    title = \"Usaldus ja rahulolu\"\n  ) +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](08-korrelatsioon_files/figure-html/scatter-jitter-1.png){width=672}\n:::\n:::\n\n\nNüüd on näha, et seos on olemas ja ta on positiivne: mida rohkem usaldust, seda rohkem\nrahulolu.\n\n> **`geom_jitter()` muudab andmeid ainult joonisel, mitte andmestikus.** Ta on\n> ettenähtud just selleks, et jaotust paremini näidata. Aga ole ettevaatlik: kui nihe on\n> liiga suur, hakkab joonis valetama.\n\n## Kovariatsioonist korrelatsioonini\n\nKuidas seda seost arvuliselt mõõta?\n\n::: {.panel-tabset}\n\n## Lihtsam seletus\n\nIdee on lihtne ja ta tuleb kahes sammus.\n\n**Esimene samm: kas hälbed käivad koos?**\n\nIga inimese kohta saab küsida kaks asja: kas ta on usalduse poolest keskmisest **üle või alla**, ja kas ta on rahulolu poolest keskmisest **üle või alla**.\n\nNüüd vaata, kuidas need kaks kokku langevad.\n\n| Usaldus | Rahulolu | Mida see näitab |\n|---|---|---|\n| üle keskmise | üle keskmise | käivad koos |\n| alla keskmise | alla keskmise | käivad koos |\n| üle keskmise | alla keskmise | käivad vastu |\n| alla keskmise | üle keskmise | käivad vastu |\n\nKui **enamik** inimesi on kahes esimeses reas, siis liiguvad muutujad samas suunas ja seos on **positiivne**. Kui enamik on kahes viimases, siis on seos **negatiivne**. Kui nad jagunevad umbes pooleks, siis seost ei ole.\n\nSelle kokkuvõtet nimetatakse **kovariatsiooniks**.\n\n**Teine samm: tee arv võrreldavaks.**\n\nKovariatsioonil on üks tüütu omadus: **tema suurus sõltub mõõtskaalast.** Kui mõõta sissetulekut eurodes, tuleb üks arv; kui tuhandetes eurodes, tuleb tuhat korda väiksem arv. Seos ise on täpselt sama, aga number on erinev.\n\nSee tähendab, et kovariatsiooni suurust ei saa millegagi võrrelda. Ta ütleb suuna, aga mitte tugevust.\n\n**Korrelatsioon lahendab selle.** Ta on kovariatsioon, mis on **taandatud mõlema muutuja hajuvusega** — nii kaob mõõtühik ära ja alles jääb puhas seos.\n\nTulemus jääb alati **−1 ja +1 vahele**, ükskõik mis skaalal muutujad on. Ja just see teebki temast kasutatava arvu: kahte korrelatsiooni saab omavahel võrrelda, kahte kovariatsiooni mitte.\n\n## Täpsem seletus\n\nAlustame sealt, kus praktikumis 6 pooleli jäime.\n\nDispersioon mõõtis, kui kaugel on väärtused **oma** keskmisest. Kirjutame ta lahti nii, et hälve on korrutatud iseendaga:\n\n$$s^2 = \\frac{\\sum(x_i-\\bar{x}) \\times (x_i-\\bar{x})}{n-1}$$\n\n**Kovariatsioon** on ainult natuke teistmoodi. Iga juhtumi puhul korrutame ühe muutuja hälbe keskmisest **teise muutuja** hälbega keskmisest:\n\n$$cov(x,y) = \\frac{\\sum(x_i-\\bar{x}) \\times (y_i-\\bar{y})}{n-1}$$\n\nMõtle läbi, mis siin toimub.\n\n* Kui mõlemad hälbed on **positiivsed** (mõlemad üle keskmise), on korrutis positiivne.\n* Kui mõlemad on **negatiivsed** (mõlemad alla keskmise), on korrutis samuti positiivne.\n* Kui nad on **eri suundades**, on korrutis negatiivne.\n\nSeega: kui hälbed on üldiselt samas suunas, tuleb kovariatsioon positiivne. Kui vastassuundades, siis negatiivne.\n\n**Korrelatsioon** on standardiseeritud kovariatsioon — jagame ta mõlema muutuja standardhälbega:\n\n$$r = \\frac{\\sum(x_i-\\bar{x}) \\times (y_i-\\bar{y})}{(n-1) \\times \\sigma_x \\times \\sigma_y}$$\n\nNii saame arvu, mis jääb alati **−1 ja +1 vahele**, sõltumata mõõtskaalast.\n\nArvutame ta käsitsi läbi. Kirjutame iga sammu eraldi reale, et oleks näha, mis toimub.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nusaldus_rahulolu <- na.omit(data[, c(\"usaldus_pol\", \"rahulolu_dem\")])\n\nhalve_x <- usaldus_rahulolu$usaldus_pol - mean(usaldus_rahulolu$usaldus_pol)\nhalve_y <- usaldus_rahulolu$rahulolu_dem - mean(usaldus_rahulolu$rahulolu_dem)\n\nkorrutiste_summa <- sum(halve_x * halve_y)\nnimetaja <- (nrow(usaldus_rahulolu) - 1) * sd(usaldus_rahulolu$usaldus_pol) * sd(usaldus_rahulolu$rahulolu_dem)\n\nkorrutiste_summa / nimetaja\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## [1] 0.59636\n```\n\n\n:::\n:::\n\n\n:::\n\n## Pearsoni korrelatsioon\n\nLoomulikult on selleks R-is funktsioon — `cor()`, mida oleme juba praktikumis 5 kasutanud.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor(usaldus_rahulolu$usaldus_pol, usaldus_rahulolu$rahulolu_dem)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## [1] 0.59636\n```\n\n\n:::\n:::\n\n\nSama arv.\n\nKuidas teda tõlgendada?\n\n| Väärtus | Tähendus |\n|---------|----------|\n| −1 | täiuslik negatiivne seos |\n| 0 | seost ei ole |\n| +1 | täiuslik positiivne seos |\n\n**Positiivne seos** tähendab, et kui ühe muutuja väärtused kasvavad, kasvavad ka teise\nomad. **Negatiivne seos** tähendab vastupidist.\n\n> Reaalsuses täiuslikku seost kahe erineva nähtuse vahel ei eksisteeri. Muutuja\n> korrelatsioon iseendaga on 1. **Kui sa näed oma andmetes korrelatsiooni, mis on väga\n> lähedal ühele, siis on peaaegu kindlasti midagi valesti** — tõenäoliselt mõõdad sa\n> kaks korda sama asja.\n\n### Hüpoteesi test\n\nKa korrelatsiooni kohta saab teha hüpoteesi testi. Nullhüpotees on, et **korrelatsioon\npopulatsioonis on null.** Funktsioon on `cor.test()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor.test(usaldus_rahulolu$usaldus_pol, usaldus_rahulolu$rahulolu_dem)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## \n## \tPearson's product-moment correlation\n## \n## data:  usaldus_rahulolu$usaldus_pol and usaldus_rahulolu$rahulolu_dem\n## t = 25.907, df = 1216, p-value < 2.2e-16\n## alternative hypothesis: true correlation is not equal to 0\n## 95 percent confidence interval:\n##  0.5589123 0.6313802\n## sample estimates:\n##     cor \n## 0.59636\n```\n\n\n:::\n:::\n\n\nVäljund on väga sarnane t-testi omale — sest loogika ongi täpselt sama. Meil on\nt-väärtus, vabadusastmed, p-väärtus ja usaldusvahemik.\n\n## Seose tugevus: R-ruut\n\nKorrelatsioonikordaja ruutu nimetatakse **determinatsioonikordajaks** ehk\n**R-ruuduks**.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor(usaldus_rahulolu$usaldus_pol, usaldus_rahulolu$rahulolu_dem)^2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## [1] 0.3556452\n```\n\n\n:::\n:::\n\n\nR-ruut näitab, **kui suur osa ühe muutuja varieeruvusest on seotud teise muutuja\nvarieeruvusega.** Antud juhul umbes 30% — usaldus poliitikute vastu aitab seletada\nligikaudu kolmandiku rahulolust demokraatiaga.\n\n> **R-ruut on tõlgendatav protsendina, korrelatsioonikordaja mitte.**\n>\n> Korrelatsioonikordaja on skaalal −1 kuni 1, aga see skaala **ei ole ühtlane**. Väärtus 0,5 ei tähenda \"poole nõrgem seos kui 1,0\" ega \"pool maksimaalsest seosest\". Kaks korda suurem *r* ei tähenda kaks korda tugevamat seost.\n>\n> R-ruut on seevastu **päris protsent**: 0,30 tähendab tõesti \"30% varieeruvusest\". Ja pane tähele, mis juhtub ruutu võttes — korrelatsioon 0,5 annab R-ruudu 0,25, seega seletab ta neljandiku, mitte poolt. Korrelatsioon 0,7 annab ligi poole.\n>\n> **Seetõttu räägi seose tugevusest R-ruudu kaudu, mitte korrelatsioonikordaja kaudu.**\n\n## Mitu korrelatsiooni korraga\n\nSeni vaatasime kahte muutujat. Praktikas tahad sa tavaliselt näha korraga kõiki paare — see annab kiire ülevaate sellest, mis su andmetes üldse omavahel seotud on.\n\nKui anda funktsioonile `cor()` mitme veeruga andmetabel, siis annabki ta **korrelatsioonimaatriksi**: iga muutuja iga teisega.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhuvipakkuvad <- data[, c(\n  \"vanus\", \"haridus\", \"sissetulek\", \"usaldus_pol\", \"rahulolu_dem\"\n)]\n\nkorrelatsioonid <- cor(huvipakkuvad, use = \"complete.obs\")\n\nround(korrelatsioonid, 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n##              vanus haridus sissetulek usaldus_pol rahulolu_dem\n## vanus         1.00    0.16      -0.35       -0.09        -0.12\n## haridus       0.16    1.00       0.27        0.22         0.19\n## sissetulek   -0.35    0.27       1.00        0.21         0.24\n## usaldus_pol  -0.09    0.22       0.21        1.00         0.59\n## rahulolu_dem -0.12    0.19       0.24        0.59         1.00\n```\n\n\n:::\n:::\n\n\nKuidas seda lugeda?\n\n* **Diagonaalil on ühed** — iga muutuja korrelatsioon iseendaga.\n* **Maatriks on sümmeetriline** — ülemine ja alumine pool on peegelpildid. Piisab ühe poole vaatamisest.\n* Iga arv on ühe **paari** korrelatsioon.\n\nTugevaim seos on usalduse ja rahulolu vahel (0,59) — see, mida me eespool juba vaatasime. Tugevaim **negatiivne** seos on vanuse ja sissetuleku vahel (−0,35): vanemad inimesed on Eestis madalama sissetulekuga.\n\n> **Argument `use = \"complete.obs\"`** ütleb, et arvutada ainult nende vastajate põhjal, kellel **kõik** need muutujad on olemas. Alternatiiv `use = \"pairwise.complete.obs\"` arvutab iga paari eraldi, kasutades kõiki, kellel just see paar olemas on.\n>\n> Vahe on oluline: teine variant kasutab rohkem andmeid, aga siis põhineb iga arv **eri inimeste hulgal**, mis teeb võrdlemise petlikuks. Kahtluse korral kasuta `\"complete.obs\"` ja ütle juhtumite arv välja.\n\n::: {.arutelu}\n**Arutelu.** Vaata hariduse rida. Haridus on positiivselt seotud sissetulekuga (0,27), usaldusega (0,22) ja rahuloluga (0,19). **Kas see tähendab, et haridus neid kolme põhjustab?** Mis muu seletus võiks olla?\n:::\n\n## Erindid: üks juhtum võib kõik ära rikkuda\n\nNüüd üks hoiatus, mis on kõige olulisem asi, mida korrelatsiooni kohta teada.\n\n**Pearsoni korrelatsioon on erakordselt tundlik üksikute ekstreemsete väärtuste suhtes.** Erind (*outlier*) on juhtum, mis on ülejäänutest väga kaugel — ja üksainus selline juhtum võib korrelatsiooni tundmatuseni muuta.\n\nTeeme katse. Meie tegelik korrelatsioon usalduse ja rahulolu vahel on:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nusaldus_ok <- usaldus_rahulolu$usaldus_pol\nrahulolu_ok <- usaldus_rahulolu$rahulolu_dem\n\ncor(usaldus_ok, rahulolu_ok)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## [1] 0.59636\n```\n\n\n:::\n:::\n\n\nNüüd lisame **ühe ainsa** vale väärtuse. Kujutame ette, et üks vastaja jäi puhastamata: tema usalduse väärtuseks on jäänud kood **99**, mis tähendas tegelikult \"ei oska öelda\".\n\n\n::: {.cell}\n\n```{.r .cell-code}\nusaldus_katki <- c(usaldus_ok, 99)\nrahulolu_katki <- c(rahulolu_ok, 5)\n\ncor(usaldus_katki, rahulolu_katki)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## [1] 0.3849845\n```\n\n\n:::\n:::\n\n\n\n\n**Korrelatsioon kukkus 0.596-lt 0.385-le** — ta kaotas umbes 35% oma väärtusest. Ja seda tegi **üks juhtum 1219-st.**\n\nVaatame, mis joonisel toimub.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nerindi_andmed <- data.frame(\n  usaldus = usaldus_katki,\n  rahulolu = rahulolu_katki\n)\n\nggplot(erindi_andmed, aes(x = usaldus, y = rahulolu)) +\n  geom_jitter(width = 0.25, height = 0.25, alpha = 0.3) +\n  labs(\n    x = \"usaldus poliitikute vastu (üks väärtus on 99)\",\n    y = \"rahulolu demokraatiaga (0-10)\",\n    title = \"Üks puhastamata väärtus tõmbab kogu pildi laiali\"\n  ) +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](08-korrelatsioon_files/figure-html/erind-joonis-1.png){width=672}\n:::\n:::\n\n\nKogu tegelik andmepilv on surutud vasakusse serva ja üks punkt istub kaugel paremal. Just see punkt otsustabki nüüd suure osa korrelatsioonist.\n\n> **Siin läheb praktikumis 4 tehtud töö arvesse.** Me nägime siis, et puhastamata koodid nagu 999 või 99 ei anna veateadet — nad on lihtsalt arvud teiste seas. Nüüd näed, mida nad tulemusega teevad.\n>\n> **Vaata alati oma muutuja miinimumi ja maksimumi enne korrelatsiooni arvutamist.** Funktsioon `summary()` teeb selle kolme sekundiga. Kui maksimum on 99 ja skaala peaks olema 0–10, siis on midagi puhastamata.\n\n## Spearmani korrelatsioon\n\nErindite probleemile on olemas ka teine lahendus — **Spearmani korrelatsioon**.\n\nIdee on lihtne. Pearsoni korrelatsioon kasutab **väärtusi endid**. Spearmani korrelatsioon kasutab ainult **järjestust**: ta asendab iga väärtuse tema järjekorranumbriga ja arvutab korrelatsiooni nende põhjal.\n\nSellest järeldub kohe kaks asja:\n\n* **erindi suurus ei loe** — kui väärtus on kõige suurem, siis ta on kõige suurem, olgu ta 11 või 99;\n* **seos ei pea olema sirgjooneline** — piisab sellest, et ta on ühesuunaline (kui üks kasvab, teine kasvab).\n\nR-is saab teda argumendiga `method = \"spearman\"`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nc(\n  pearson = cor(usaldus_ok, rahulolu_ok),\n  spearman = cor(usaldus_ok, rahulolu_ok, method = \"spearman\")\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n##   pearson  spearman \n## 0.5963600 0.5949891\n```\n\n\n:::\n:::\n\n\nMeie korrastatud andmetes on nad **praktiliselt samad**. See ei ole ebaõnnestunud näide — see on hea uudis: kui kaks korrelatsiooni langevad kokku, siis tähendab see, et seos on ühtlane ja ekstreemseid väärtusi ei ole.\n\nAga vaata nüüd, mis juhtub sellesama puhastamata 99-ga:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nc(\n  pearson = cor(usaldus_katki, rahulolu_katki),\n  spearman = cor(usaldus_katki, rahulolu_katki, method = \"spearman\")\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n##   pearson  spearman \n## 0.3849845 0.5940081\n```\n\n\n:::\n:::\n\n\n**Pearson kukkus kolmandiku võrra. Spearman ei liikunud praktiliselt üldse.** Talle on ükskõik, kas kõige suurem väärtus on 10 või 99 — ta on ikka kõige suurem.\n\n### Kumba kasutada?\n\n| Kasuta **Pearsonit**, kui | Kasuta **Spearmanit**, kui |\n|---|---|\n| mõlemad muutujad on pidevad | muutujad on ordinaalsed |\n| seos näeb jooniselt sirgjooneline välja | seos on ühesuunaline, aga kõver |\n| ekstreemseid väärtusi ei ole | andmetes on erindeid |\n| tahad hiljem regressiooni teha | tahad lihtsalt seost kirjeldada |\n\n> **Praktiline soovitus: arvuta mõlemad.** See on üks lisarida koodi.\n>\n> Kui nad on **sarnased**, siis on kõik hästi ja raporteeri Pearson (ta on tavapärasem ja seotud regressiooniga).\n>\n> Kui nad on **märgatavalt erinevad**, siis on see märk, et midagi tasub uurida: kas on erindeid, kas seos on kõver, kas mõni väärtus on puhastamata. **Erinevus ise on informatsioon.**\n\n## Kuidas seda kirja panna\n\n::: {.callout-tip title=\"Kuidas seda kirja panna\"}\nKorrelatsiooni esitamisel peab kirjas olema korrelatsioonikordaja, p-väärtus, usaldusvahemik, juhtumite arv ja **seose sisuline tõlgendus**.\n\n**Usaldus poliitikute vastu ja rahulolu demokraatiaga on omavahel tugevalt seotud (r = 0,60; p < 0,001; 95% usaldusvahemik 0,56–0,63; n = 1218). Seos on positiivne: mida rohkem inimene poliitikuid usaldab, seda rahulolevam ta demokraatia toimimisega on. Determinatsioonikordaja (r² = 0,36) näitab, et need kaks nähtust jagavad ligikaudu kolmandiku oma varieeruvusest.**\n\nKolm asja, mida vältida:\n\n* **korrelatsioon ilma juhtumite arvuta** — sama *r* tähendab väikeses ja suures valimis väga erinevat kindlust;\n* **seose tugevuse hindamine korrelatsioonikordaja järgi** — kasuta selleks R-ruutu (vt ülal);\n* **\"põhjustab\"** — vt hoiatust allpool.\n\n> **Ja kõige tähtsam hoiatus. Korrelatsioon ei ole põhjuslikkus.** See, et kaks nähtust käivad koos, ei ütle midagi selle kohta, kumb kumba mõjutab — ega sellegi kohta, kas nad üksteist üldse mõjutavad. Sama hästi võib mõlemat põhjustada midagi kolmandat.\n>\n> Kirjuta **\"on seotud\"** ja **\"käib koos\"**, mitte \"põhjustab\" ja \"mõjutab\", kui sul ei ole põhjuslikkuse väitmiseks eraldi head argumenti.\n:::\n\n## Harjutused\n\n::: {.harjutus}\n**1. Korrelatsioon.** Arvuta korrelatsioon muutujate `usaldus` ja `rahulolu_dem` vahel. Tee ka hüpoteesi test. Kui tugev seos on ja kui suure osa varieeruvusest ta seletab?\n\n**2. Joonis.** Tee nende kahe muutuja kohta hajuvusdiagramm. Kas seos on jooniselt näha?\n\n**3. Korrelatsioonimaatriks.** Tee korrelatsioonimaatriks, kus on sees `ranne`, `usaldus`, `haridus` ja `vanus`. Milline paar on kõige tugevamalt seotud? Kas mõni seos üllatab?\n\n**4. Spearman.** Arvuta kõikide nende paaride kohta ka Spearmani korrelatsioon. Kas mõne paari puhul on vahe märgatav? Kui jah, siis vaata seda paari joonisel — mis seal toimub?\n\n**5. Erind.** Vali üks muutujapaar ja lisa sinna ise üks ekstreemne väärtus. Kui palju korrelatsioon muutub? Proovi ka, kui palju on vaja väärtust suurendada, et Spearman lõpuks liikuma hakkaks.\n:::\n",
    "supporting": [
      "08-korrelatsioon_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}