{
  "hash": "83b081b96a14db737550f14f6bd200aa",
  "result": {
    "engine": "knitr",
    "markdown": "# 6. Valim, ebakindlus ja hüpoteeside testimine\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\nlibrary(ggplot2)\nload(\"data/ess11_ee_clean.rdata\")\n```\n:::\n\n\nSiiani oleme kirjeldanud seda, mida me oma andmetes näeme, ja teinud andmed selleks korda. Nüüd hakkame küsima midagi palju julgemat: **mida saame me nende 1293 inimese põhjal öelda kogu Eesti kohta?**\n\nSee praktikum käib läbi terve teekonna: kust tuleb ebakindlus, kuidas seda mõõta ja kuidas selle põhjal **otsuseid teha**.\n\nSee on kursuse kõige raskem osa. Ta on ka kõige olulisem — kõik ülejäänu, t-test,\nkorrelatsioon, regressioon, logistiline regressioon, toetub täpselt sellele loogikale,\nmille me siin läbi käime. Kui see koht selgeks saab, siis on kõik ülejäänu variatsioon\nsamal teemal.\n\n> Seetõttu on siin peatükis kõige tähtsamad kohad esitatud **kahel viisil**. Sakid\n> \"Lihtsam seletus\" ja \"Täpsem seletus\" räägivad samast asjast — üks pilte ja katseid\n> kasutades, teine valemitega. Vali see, mis sulle sobib. Kui üks jääb segaseks, proovi\n> teist.\n\n## Valim ja populatsioon\n\nKaks mõistet, mis tuleb selgeks saada.\n\n**Populatsioon** on kogu see hulk, kelle kohta me tahame midagi öelda. Meie puhul: kõik\nEesti elanikud alates 15. eluaastast. Neid on umbes 1,2 miljonit.\n\n**Valim** on see osa populatsioonist, kelle kohta meil päriselt andmed on. Meie puhul:\n1293 inimest.\n\nKõige olulisem asi valimi juures on see, et ta on **juhuvalim**. See tähendab, et igal\npopulatsiooni liikmel oli sama tõenäosus valimisse sattuda. Mitte vabatahtlikud, mitte\nneed, keda oli lihtne kätte saada — juhuslikult valitud.\n\n> **Miks juhuslikkus on nii oluline?** Sest ainult juhuvalimi puhul saame me matemaatiliselt\n> hinnata, kui kaugel meie valimist arvutatud arv võib olla tõesest arvust\n> populatsioonis. Mittejuhusliku valimi puhul ei ole mingit võimalust seda teada. Selline\n> valim ei ole \"natuke halvem\" — ta on üldistuste tegemiseks lihtsalt kasutu.\n\nJa siit tuleb probleem. Juhuslikkus tähendab, et **meie valim ei ole populatsiooni täpne\nkoopia.** Mõned inimesed sattusid valimisse, teised mitte. Kui me võtaksime uue valimi,\noleks ta natuke teistsugune. Ja seega oleks ka iga arv, mille me valimist arvutame,\nnatuke teistsugune.\n\nMeie valimi keskmine vanus on:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(data$vanus, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## [1] 50.07309\n```\n\n\n:::\n:::\n\n\nAga Eesti tegelik keskmine vanus ei ole täpselt see. Küsimus on: **kui kaugel ta olla\nvõib?**\n\n## Kust tuleb ebakindlus\n\n::: {.panel-tabset}\n\n## Lihtsam seletus\n\nTeeme katse. Meil ei ole võimalik Eestist uut valimit võtta, aga me saame teha midagi\nsarnast: **võtta oma 1293 inimesest korduvalt väiksemaid juhuvalimeid** ja vaadata,\nkuidas keskmine iga kord muutub.\n\nSelleks on kaks funktsiooni:\n\n* `sample()` võtab juhusliku valimi. Esimene argument on see, millest valida, argument\n  `size` ütleb, mitu juhtumit võtta, ja argument `replace = TRUE` ütleb, et sama inimene\n  võib mitu korda valituks osutuda.\n* `set.seed()` fikseerib juhuslikkuse. Arvuti juhuarvud ei ole päriselt juhuslikud —\n  nad arvutatakse mingist algväärtusest. Kui sa selle algväärtuse fikseerid, saad iga\n  kord sama tulemuse.\n\n> **Miks `replace = TRUE`?** Sest me teeskleme, et võtame valimeid **Eesti\n> elanikkonnast**, mitte oma 1286 vastajast. Elanikkond on meie andmestikust tuhat korda\n> suurem, seega on tõenäosus sama inimene kaks korda saada praktiliselt olematu.\n> Tagasipanekuga valimine jäljendab seda olukorda.\n\n> **Kasuta alati `set.seed()`**, kui su koodis on juhuslikkust. Ilma selleta saad sa iga\n> kord erineva tulemuse ja sa ei suuda oma enda analüüsi korrata. Number sulgudes võib\n> olla ükskõik milline — oluline on ainult see, et ta oleks alati sama.\n\nVõtame ühe valimi, sada inimest:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2026)\n\nvanused <- na.omit(data$vanus)\n\nvalim1 <- sample(vanused, size = 100, replace = TRUE)\nmean(valim1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## [1] 49.46\n```\n\n\n:::\n:::\n\n\nJa veel ühe:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvalim2 <- sample(vanused, size = 100, replace = TRUE)\nmean(valim2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## [1] 48.67\n```\n\n\n:::\n:::\n\n\nErinev arv. Ja kolmas oleks jälle erinev.\n\nTeeme seda nüüd tuhat korda. Selleks on funktsioon `replicate()`, mis kordab sama\ntegevust nii mitu korda, kui palju sa ütled, ja kogub tulemused kokku. Esimene argument\non korduste arv, teine on tegevus.\n\nSelleks et kood loetavaks jääks, teeme kõigepealt **oma funktsiooni**, mis võtab ühe valimi ja annab tagasi tema keskmise. Siis kordame teda tuhat korda.\n\nFunktsiooni loomine käib nii: nimi, `<-`, sõna `function`, ümarsulgudes sisendi nimi ja looksulgudes see, mida teha. Viimane rida funktsiooni sees on see, mille ta tagastab. Nimetame ta `uhe_valimi_keskmine()` — ta võtab sisendiks valimi suuruse ja annab tagasi selle valimi keskmise.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2026)\n\nuhe_valimi_keskmine <- function(valimi_suurus) {\n  valim <- sample(vanused, size = valimi_suurus, replace = TRUE)\n  mean(valim)\n}\n\nkeskmised <- replicate(1000, uhe_valimi_keskmine(100))\n\nlength(keskmised)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## [1] 1000\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(keskmised)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## [1] 49.46 48.67 48.44 50.90 51.54 52.63\n```\n\n\n:::\n:::\n\n\nMeil on nüüd tuhat keskmist. Vaatame, kuidas nad jaotuvad.\n\nJoonisel kasutame ka funktsiooni `geom_vline()`, mis tõmbab püstise joone. Argument `xintercept` ütleb, millise x-telje väärtuse juurde ta tuleb. Argument `bins` funktsioonis `geom_histogram()` määrab, mitmeks kastiks skaala jagatakse.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data.frame(keskmised), aes(x = keskmised)) +\n  geom_histogram(bins = 30, fill = \"dodgerblue3\", color = \"white\") +\n  geom_vline(xintercept = mean(vanused), color = \"firebrick3\", linewidth = 1) +\n  labs(\n    x = \"valimi keskmine vanus\",\n    y = \"kui mitu korda\",\n    title = \"1000 valimi keskmised, iga valim n = 100\"\n  ) +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](06-valim-ja-hupoteesid_files/figure-html/sim-joonis-1.png){width=672}\n:::\n:::\n\n\n**Vaata seda joonist tähelepanelikult. Siin on peidus kogu järeldava statistika mõte.**\n\nPunane joon on kõigi 1293 inimese tegelik keskmine. Sinised tulbad on need tuhat\nkeskmist, mille me juhuvalimitest saime.\n\nKolm asja, mida tähele panna:\n\n1. **Keskmised ei ole kõik ühesugused.** Nad hajuvad. See ongi ebakindlus.\n2. **Nad on koondunud tõese väärtuse ümber.** Ükski üksik valim ei taba täpselt\n   õigesti, aga nad ei eksi ka süstemaatiliselt ühes suunas.\n3. **Jaotus on kellukesekujuline.** See ei ole juhus — see on **normaaljaotus** ja ta\n   tekib alati, kui sa piisavalt palju juhuvalimeid võtad.\n\nKui hajusad nad on? Selle saame välja arvutada.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsd(keskmised)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## [1] 1.801523\n```\n\n\n:::\n:::\n\n\n**See arv ongi see, mida me otsime.** Ta ütleb, kui palju üks üksik valimi keskmine\ntüüpiliselt tõesest väärtusest eksib.\n\n### Mis juhtub, kui valim on suurem?\n\nTeeme sama katse kolme erineva valimisuurusega.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2026)\n\nk_50 <- replicate(1000, uhe_valimi_keskmine(50))\nk_200 <- replicate(1000, uhe_valimi_keskmine(200))\nk_800 <- replicate(1000, uhe_valimi_keskmine(800))\n\nc(\n  n50 = sd(k_50),\n  n200 = sd(k_200),\n  n800 = sd(k_800)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n##       n50      n200      n800 \n## 2.5246819 1.2875353 0.6536432\n```\n\n\n:::\n:::\n\n\nMida suurem valim, seda **väiksem** hajuvus. Vaatame ka pilti.\n\nJoonise jaoks paneme kolm tulemust ühte andmetabelisse. Funktsioon `rep()` kordab\nväärtusi; argument `each` ütleb, mitu korda igaüht järjest korrata.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsim <- data.frame(\n  keskmine = c(k_50, k_200, k_800),\n  valim = rep(c(\"n = 50\", \"n = 200\", \"n = 800\"), each = 1000)\n)\n\nsim$valim <- factor(sim$valim, levels = c(\"n = 50\", \"n = 200\", \"n = 800\"))\n\nggplot(sim, aes(x = keskmine, fill = valim)) +\n  geom_density(alpha = 0.5) +\n  geom_vline(xintercept = mean(vanused), color = \"firebrick3\", linewidth = 1) +\n  labs(\n    x = \"valimi keskmine vanus\",\n    y = \"tihedus\",\n    title = \"Mida suurem valim, seda vähem ebakindlust\",\n    fill = NULL\n  ) +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](06-valim-ja-hupoteesid_files/figure-html/sim-suurused-joonis-1.png){width=672}\n:::\n:::\n\n\n> **See on kogu asja tuum.** Rohkem andmeid tähendab vähem ebakindlust. Mitte seetõttu,\n> et suur valim oleks kuidagi \"õigem\", vaid seetõttu, et suure valimi keskmised hajuvad\n> tõese väärtuse ümber vähem.\n\nSama loogika kehtib ka hajuvuse kohta andmetes endas: mida hajusamad on väärtused\nvalimis, seda hajusamad on ka valimite keskmised, ja seda ebakindlamad me oleme.\n\nNüüd on sul olemas kogu intuitsioon, mida vaja. Järgmises sakis on sama asi valemitega —\nja seal selgub, et **seda hajuvust ei olegi vaja simuleerida.** Selle saab välja\narvutada ühest ainsast valimist.\n\n## Täpsem seletus\n\nVaatame sama asja arvutuskäiguna. Alustame keskmisest.\n\n**Aritmeetiline keskmine** on väärtuste summa jagatud väärtuste arvuga:\n\n$$\\bar{X} = \\frac{\\sum_{i=1}^n{x_i}}{n}$$\n\nArvutame ta kõigepealt \"käsitsi\" ja siis funktsiooniga, et näha, et tulemus on sama.\n\n> Funktsioon `as.vector()` teeb objektist tavalise vektori. Seda on siin vaja\n> sellepärast, et `na.omit()` jätab objekti külge lisainfo selle kohta, millised read ta\n> eemaldas, ja see segaks hilisemaid arvutusi.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvanus <- na.omit(data$vanus)\nvanus <- as.vector(vanus)\n\nsum(vanus) / length(vanus)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## [1] 50.07309\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(vanus)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## [1] 50.07309\n```\n\n\n:::\n:::\n\n\nNüüd hajuvus. Meid huvitab, kui kaugel keskmisest väärtused tüüpiliselt on. Esimene\nmõte oleks arvutada keskmine kaugus keskmisest — aga see ei tööta.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkaugus <- vanus - mean(vanus)\nmean(kaugus)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## [1] 7.470092e-15\n```\n\n\n:::\n:::\n\n\nVastus on praktiliselt null, sest positiivsed ja negatiivsed kõrvalekalded tühistavad\nüksteist. Keskmine kaugus keskmisest **on alati null** — see on keskmise definitsioon.\n\n> **Mis on see `e-15`?** See on **teaduslik notatsioon**. Väga suuri või väga väikeseid\n> arve kuvab R niimoodi, et nad ekraanile ära mahuksid. `2.7e-15` tähendab\n> $2{,}7 \\times 10^{-15}$ ehk üliväikest arvu. Praktiliselt null.\n>\n> Kui sa ei taha teaduslikku notatsiooni näha, jooksuta käsk `options(scipen = 5)`.\n>\n> **Jäta see meelde.** Sa kohtad seda regressioonitabelites pidevalt ja siis on hilja\n> imestada.\n\nLahendus on võtta kaugused **ruutu**, mis teeb kõik positiivseks. Nii saame\n**dispersiooni** (*variance*):\n\n$$var = \\frac{\\sum(x_i-\\bar{x})^2}{n}$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nruutkaugus <- kaugus^2\nsum(ruutkaugus) / length(ruutkaugus)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## [1] 324.9356\n```\n\n\n:::\n:::\n\n\nRuutu võtmine ajas aga mõõtühiku sassi — nüüd on tulemus ruutaastates. Võtame ruutjuure\ntagasi ja saame **standardhälbe**:\n\n$$sd = \\sqrt{\\frac{\\sum(x_i-\\bar{x})^2}{n}}$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(sum(ruutkaugus) / length(ruutkaugus))^0.5\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## [1] 18.02597\n```\n\n\n:::\n:::\n\n\n### Parandus, mis on vajalik\n\nSiin on üks konks. Meie valimis ei ole populatsiooni kõige haruldasemaid, kõige\näärmuslikumaid väärtusi — nad on haruldased just sellepärast, et nad valimisse\ntõenäoliselt ei satu. Seetõttu **alahindab valimi hajuvus alati populatsiooni\nhajuvust.**\n\nSelle parandamiseks jagatakse mitte $n$-iga, vaid $n-1$-ga:\n\n$$sd = \\sqrt{\\frac{\\sum(x_i-\\bar{x})^2}{n-1}}$$\n\nJust seda teevad R-i funktsioonid `var()` ja `sd()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvar(vanus)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## [1] 325.1884\n```\n\n\n:::\n\n```{.r .cell-code}\nsd(vanus)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## [1] 18.03298\n```\n\n\n:::\n:::\n\n\nSeda $n-1$ nimetatakse **vabadusastmeteks** (*degrees of freedom*).\n\n> **Mida vabadusastmed tähendavad?** Kõige lihtsam on mõelda neist kui **vabast infost** andmetes.\n>\n> Oletame, et sul on viis arvu ja sa juba tead nende keskmist. Kui nüüd neli arvu ette anda, siis viies **ei ole enam vaba** — ta on üheselt määratud, sest keskmine peab kokku tulema. Viiest arvust on vaba ainult neli.\n>\n> Üldiselt: iga suurus, mille sa **oma andmetest välja arvutad** ja hiljem kasutad, võtab ühe vabadusastme ära. Standardhälbe arvutamiseks oli meil vaja keskmist — see maksis ühe vabadusastme, seega jäi järele $n-1$.\n>\n> Sellepärast sõltub vabadusastmete arv kahest asjast: **kui palju juhtumeid on** ja **kui palju suurusi on andmetest juba välja arvutatud**. Regressioonis, kus arvutatakse mitu koefitsienti, kaob vabadusastmeid rohkem.\n\n### Standardviga\n\nNüüd kõige tähtsam samm. Meid ei huvita tegelikult mitte vanuse hajuvus, vaid\n**keskmiste hajuvus** — täpselt see, mida eelmises sakis simuleerisime.\n\nJuhuvalimi puhul kehtib matemaatiline seaduspära, mis lubab selle **ühest ainsast\nvalimist välja arvutada.** Seda suurust nimetatakse **standardveaks**:\n\n$$se_{\\bar{x}} = \\frac{sd}{\\sqrt{n}}$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsd(vanus) / length(vanus)^0.5\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## [1] 0.50286\n```\n\n\n:::\n:::\n\n\nKontrollime, kas see klapib simulatsiooniga. Simulatsioonis kasutasime valimeid\nsuurusega 100:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsd(vanus) / 100^0.5\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## [1] 1.803298\n```\n\n\n:::\n:::\n\n\nJa simulatsioonist saime:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2026)\n\nuhe_valimi_keskmine <- function(valimi_suurus) {\n  valim <- sample(vanus, size = valimi_suurus, replace = TRUE)\n  mean(valim)\n}\n\nsd(replicate(1000, uhe_valimi_keskmine(100)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## [1] 1.801523\n```\n\n\n:::\n:::\n\n\n**Praktiliselt sama arv.** Valem ennustas täpselt ära selle, mida simulatsioon näitas —\nilma et oleks olnud vaja tuhat valimit võtta.\n\n> **Vaata valemit ja mõtle, mida ta ütleb.** Standardviga on murd, kus lugejas on\n> hajuvus ja nimetajas ruutjuur valimi suurusest.\n>\n> * Suurem hajuvus → suurem standardviga → rohkem ebakindlust.\n> * Suurem valim → suurem nimetaja → väiksem standardviga → vähem ebakindlust.\n>\n> Täpselt see, mida simulatsioon näitas. Ainult et nüüd me ka teame, **miks**.\n>\n> Pane tähele ka ruutjuurt: valimi kahekordistamine ei poolita ebakindlust, vaid\n> vähendab teda ainult umbes 30% võrra. Täpsuse ostmine läheb aina kallimaks.\n\n:::\n\n## Normaaljaotus ja tõenäosus\n\nMiks on oluline, et need keskmised jaotuvad normaaljaotuse järgi? Sest normaaljaotusel\non üks väga kasulik omadus: **me teame täpselt, kui suur osa väärtustest asub kui kaugel\nkeskmisest.**\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](06-valim-ja-hupoteesid_files/figure-html/normaaljaotus-joonis-1.png){width=672}\n:::\n:::\n\n\nUmbes 68% väärtustest jääb ühe standardhälbe kaugusele keskmisest, umbes 95% kahe\nstandardhälbe kaugusele ja umbes 99,7% kolme kaugusele.\n\nKaugust keskmisest standardhälvetes nimetatakse **z-skooriks**. Kui z-skoor on 1, siis\non väärtus ühe standardhälbe kaugusel keskmisest.\n\nFunktsioon `pnorm()` ütleb, kui suur osa normaaljaotusest jääb antud z-skoorist\nallapoole (vasakule).\n\nArgument `lower.tail` määrab, kummalt poolt vaadata: vaikimisi `TRUE` annab osakaalu allpool antud väärtust, `FALSE` annab ülalpool.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npnorm(1.96)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## [1] 0.9750021\n```\n\n\n:::\n\n```{.r .cell-code}\npnorm(1.96, lower.tail = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## [1] 0.0249979\n```\n\n\n:::\n:::\n\n\nEsimene arv ütleb, et 97,5% väärtustest on väiksemad kui 1,96 standardhälvet üle keskmise. Teine pöörab küsimuse ümber: 2,5% väärtustest on sellest suuremad.\n\nFunktsioon `qnorm()` teeb vastupidist — annab z-skoori, millele vastab teatud osakaal.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqnorm(0.025)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## [1] -1.959964\n```\n\n\n:::\n\n```{.r .cell-code}\nqnorm(0.975)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## [1] 1.959964\n```\n\n\n:::\n:::\n\n\nSama arv, ainult märk on erinev, sest normaaljaotus on sümmeetriline. **Arv 1,96 on\nselle kursuse üks olulisemaid arve.** Tema vahele jääb 95% normaaljaotusest.\n\n### T-jaotus\n\nVäikese valimi puhul kasutatakse normaaljaotuse asemel **t-jaotust**. Ta näeb\nnormaaljaotusega väga sarnane välja, kuid on servadest natuke laiemaks venitatud — sest\nväikese valimi puhul on rohkem ebakindlust.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](06-valim-ja-hupoteesid_files/figure-html/t-jaotus-joonis-1.png){width=672}\n:::\n:::\n\n\nMida vähem vabadusastmeid, seda lamedam on jaotus ja seda paksemad on tema sabad — ehk seda tõenäolisem on näha keskmisest kaugel olevat väärtust. Kümne vabadusastme juures on vahe normaaljaotusest juba väike.\n\nT-jaotuse kuju sõltub vabadusastmete arvust. Funktsioon `qt()` töötab nagu `qnorm()`,\nkuid vajab lisaks argumenti `df` (*degrees of freedom*).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqt(0.975, df = 10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## [1] 2.228139\n```\n\n\n:::\n\n```{.r .cell-code}\nqt(0.975, df = 100)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## [1] 1.983972\n```\n\n\n:::\n\n```{.r .cell-code}\nqt(0.975, df = 1000)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## [1] 1.962339\n```\n\n\n:::\n:::\n\n\nMida rohkem juhtumeid, seda lähemale jõuab t-jaotus normaaljaotusele ja seda lähemale\njõuab piirväärtus arvule 1,96.\n\n> **Rusikareegel:** kui juhtumeid on paarsada või rohkem, on piirväärtus umbes 2. Meie\n> andmestikuga ei ole vahet, kas kasutada normaaljaotust või t-jaotust.\n\n## Usaldusvahemikud\n\nNüüd saame kokku panna kõik, mida vaja.\n\n**Usaldusvahemik** näitab vahemikku, kuhu tõenäoliselt jääb tõene väärtus\npopulatsioonis. 95% usaldusvahemik ulatub 1,96 standardviga keskmisest mõlemale poole.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nk_vanus <- mean(vanus)\nsviga <- sd(vanus) / length(vanus)^0.5\n\nc(\n  alumine = k_vanus - 1.96 * sviga,\n  keskmine = k_vanus,\n  ylemine = k_vanus + 1.96 * sviga\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n##  alumine keskmine  ylemine \n## 49.08749 50.07309 51.05870\n```\n\n\n:::\n:::\n\n\nKui tahame olla väga täpsed, kasutame t-jaotust:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nc(\n  alumine = k_vanus + qt(0.025, df = length(vanus) - 1) * sviga,\n  ylemine = k_vanus + qt(0.975, df = length(vanus) - 1) * sviga\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n##  alumine  ylemine \n## 49.08658 51.05961\n```\n\n\n:::\n:::\n\n\nVahe on tühine, nagu ennustatud.\n\n> **Mida usaldusvahemik täpselt tähendab?** Kui me võtaksime Eestist lõpmata palju kordi\n> sama suure juhuvalimi ja arvutaksime iga kord usaldusvahemiku, siis 95% nendest\n> vahemikest sisaldaks tõest keskmist.\n>\n> Igapäevases kasutuses tõlgendatakse teda lihtsamalt: see on vahemik, kus tõene\n> väärtus **tõenäoliselt** asub. Rangelt võttes ei ole see päris täpne, aga praktilise\n> töö jaoks piisab.\n\n## Kuidas seda kirja panna\n\n::: {.callout-tip title=\"Kuidas seda kirja panna\"}\nKeskmist ei tohi kunagi esitada ilma ebakindluse hinnanguta. Miinimum on standardhälve;\nparem on lisada ka usaldusvahemik.\n\n**Vastajate keskmine vanus oli 50,1 aastat (standardhälve 18,3; 95% usaldusvahemik\n49,1–51,1; n = 1286). Valimi suurust arvestades saab keskmist vanust hinnata\nküllaltki täpselt.**\n\nPane tähele:\n\n* **standardhälve** kirjeldab, kui hajusad on inimesed;\n* **standardviga ja usaldusvahemik** kirjeldavad, kui kindlad me keskmises oleme.\n\nNeed kaks aetakse pidevalt segamini. **Standardhälve on andmete omadus** — ta kirjeldab, kui erinevad inimesed omavahel on, ja ta ei kahane, kui sa rohkem andmeid kogud. Kui eestimaalaste vanused on hajusad, siis nad on hajusad ka siis, kui sa küsitled kümme korda rohkem inimesi.\n\n**Standardviga on sinu teadmise omadus** — ta kirjeldab, kui täpselt sa keskmist tead. Ja tema **kahaneb siis, kui andmete hulk suureneb**: mida rohkem inimesi sa küsitled, seda täpsemalt sa keskmist tead, kuigi inimesed ise jäävad täpselt sama erinevaks.\n:::\n\n## Null- ja alternatiivhüpotees\n\nPeaaegu iga statistiline test on üles ehitatud ühtemoodi. Meil on kaks väidet.\n\n* **Nullhüpotees.** See väärtus, mida me andmetes näeme, ei erine mingist kindlast\n  hüpoteetilisest väärtusest. Enamasti on see hüpoteetiline väärtus **null**. Lühidalt:\n  **seost ei ole.**\n* **Alternatiivne hüpotees.** Erinevus on olemas. Lühidalt: **seos on olemas.**\n\nTest ei tõesta kumbagi. Ta ütleb ainult: **kui nullhüpotees oleks realsuses tõsi, kui tõenäoline\noleks siis näha andmetes seda, mida me näeme?** Kui see tõenäosus on väga väike, siis järeldame,\net nullhüpotees ilmselt ei kehti. Ehk siis kui see tõenäosus, et me näeme oma andmetes seda, mida me näeme olukorras, kus pärielt on tõene null-hüpotees, on väga väike, siis me järeldame, et null-hüpotees ei ole tõene. Meie andmed ei ole väga suure tõenäosusega tulnud populatsioonist, kus null hüpotees on tõene. \n\n## Mis on p-väärtus?\n\nEnne kui ühtegi testi teeme, tuleb selgeks saada see arv, mille järgi me kõik oma otsused teeme.\n\n**P-väärtus on tõenäosus näha oma andmetes sellist tulemust (või veel ekstreemsemat), kui nullhüpotees oleks tõsi.**\n\nLoe see lause veel kord läbi. Ta on tinglik: \"kui nullhüpotees oleks tõsi\". P-väärtus ei ütle sulle, kas nullhüpotees on tõsi — ta ütleb, kui hästi sinu andmed sellega kokku sobiksid.\n\nMõtle sellest nii. Sa oletad korraks, et seost ei ole. Siis vaatad oma andmeid ja küsid: **kui ebatavalised need andmed sellise oletuse juures oleksid?**\n\n* Kui p-väärtus on **suur** (näiteks 0,60), siis on sinu andmed sellise oletusega täiesti kooskõlas. Midagi kummalist ei ole.\n* Kui p-väärtus on **väike** (näiteks 0,002), siis oleksid sinu andmed sellise oletuse juures väga ebatavalised. Järelikult on oletus ilmselt vale ja seos on olemas.\n\nPraktilises kasutuses tõlgendatakse teda lühemalt: **tõenäosus eksida, kui me väidame, et seos on päriselt olemas.**\n\n> **Statistiline tava on 5%.** Kui p-väärtus on väiksem kui 0,05 — ehk tõenäosus eksida on alla 5% — siis ütleme, et erinevus on **statistiliselt oluline**. See piir ei ole loodusseadus, vaid kokkulepe. Mõnes valdkonnas kasutatakse rangemaid piire (1% või 0,1%).\n>\n> Sama asja kohta öeldakse vahel ka \"95% usaldusnivoo\" — see on lihtsalt teine pool samast arvust. 5% tõenäosus eksida tähendab 95% kindlust.\n\n**Mida p-väärtus EI ole.** Kolm väärarusaama, mis on nii levinud, et neid tasub eraldi välja tuua.\n\n* Ta **ei ole** tõenäosus, et nullhüpotees on tõsi.\n* Ta **ei ütle midagi selle kohta, kui suur** seos on. Väga väike p-väärtus võib käia täiesti tühise erinevuse kohta — vaata allpool osa statistilise ja sisulise olulisuse kohta.\n* Ta **ei ole** tõenäosus, et sinu tulemus kordub, kui uuringut korrata.\n\n> **P-väärtus on kogu järgneva kursuse võti.** Ta näeb täpselt samasugune välja ja teda tõlgendatakse täpselt sama moodi t-testi, korrelatsiooni, regressiooni ja logistilise regressiooni juures. Kui ta siin selgeks saab, siis on kõik ülejäänu variatsioon samal teemal.\n\n## Otsustamine usaldusvahemiku abil\n\nNüüd on meil kõik olemas, mida otsustamiseks vaja. Ja tähelepanuväärne on see, et **uut arvutust ei ole vaja teha** — usaldusvahemik, mille me juba arvutasime, vastab hüpoteesi küsimusele ära.\n\nMeie valimi keskmine vanus on 50.1 ja 95% usaldusvahemik ulatub 49.1-st 51.1-ni.\n\nKüsime nüüd: **kas Eesti elanike keskmine vanus võiks olla 52?**\n\nArv 52 jääb sellest vahemikust **välja**. Meie andmetega on ta raskesti ühildatav — kui tõene keskmine oleks 52, siis oleks väga ebatavaline näha valimit, mille keskmine on 50.1.\n\nJa **kas ta võiks olla 50?** See jääb vahemikku sisse. Seda me välistada ei saa.\n\n> **See ongi hüpoteesi test.** Kogu ülejäänu, mis järgmises praktikumis tuleb, on selle sama küsimuse täpsem sõnastus ja mugavam arvutamine:\n>\n> * kui võrreldav väärtus jääb **usaldusvahemikku sisse**, siis ei saa me välistada, et ta ongi tõene väärtus — erinevus **ei ole** statistiliselt oluline;\n> * kui ta jääb **väljapoole**, siis on erinevus statistiliselt oluline.\n>\n> P-väärtus ütleb sama asja täpsemalt: mitte \"jääb sisse või välja\", vaid \"kui kaugel piirist\".\n\n::: {.arutelu}\n**Arutelu.** Kui me arvutaksime 99% usaldusvahemiku, siis ta oleks laiem. **Kas arv 52 võiks siis vahemikku sisse jääda?** Ja mida see tähendaks meie järelduse jaoks?\n:::\n\n## Kokkuvõte\n\nSelles praktikumis käisime läbi kogu järeldava statistika loogika:\n\n* **valim ja populatsioon** — miks juhuslikkus on hädavajalik;\n* **ebakindlus** — kust ta tuleb ja miks ta valimi kasvades kahaneb;\n* **standardviga ja usaldusvahemik** — kuidas ebakindlust arvuliselt väljendada;\n* **p-väärtus** — arv, mille järgi otsuseid tehakse;\n* **otsustamine usaldusvahemiku abil** — hüpoteesi testi kõige lihtsam vorm.\n\nKogu ülejäänu sellel kursusel on selle sama loogika kordamine erinevate seoste peal. Järgmises praktikumis võrdleme keskmisi, siis kahe pideva muutuja seost, siis regressioonimudeleid — aga p-väärtus tähendab igal pool täpselt sama asja.\n\n## Harjutused\n\n::: {.harjutus}\n**1. Simulatsioon.** Korda praktikumis tehtud simulatsiooni muutujaga `usaldus_pol`. Võta 1000 valimit suurusega 100 ja vaata nende keskmiste jaotust. Mis on selle jaotuse standardhälve?\n\n**2. Valimi suurus.** Tee sama simulatsioon valimi suurusega 25 ja 400. Kui palju hajuvus muutub? Kontrolli valemiga, kas tulemus vastab ootusele.\n\n**3. Usaldusvahemik.** Arvuta 95% usaldusvahemik muutuja `rahulolu_dem` keskmise ümber. Arvuta seejärel ka 99% usaldusvahemik — mis muutub ja miks?\n\n**4. Standardviga käsitsi.** Arvuta muutuja `haridus` standardviga käsitsi (standardhälve jagatud ruutjuurega juhtumite arvust) ja kontrolli tulemust funktsiooniga `t.test()`.\n\n**5. Ühe grupi test.** Testi, kas Eesti elanike keskmine rahulolu demokraatiaga erineb skaala keskpunktist 5. Sõnasta null- ja alternatiivhüpotees **enne** testi tegemist.\n\n**6. P-väärtus käsitsi.** Võta eelmise harjutuse t-väärtus ja arvuta p-väärtus ise, funktsiooniga `pt()`. Kontrolli, et sinu tulemus klapib `t.test()` omaga. Ära unusta kumbagi kahest tehtest.\n:::\n",
    "supporting": [
      "06-valim-ja-hupoteesid_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}